# Allocation of uncertainty among possible data values: probability distributions

## The difference between Statistics and Probability Theory

_Statistics_ is the study of collective properties of collections of data. It does not imply that there is any uncertainty.

_Probability theory_ is the quantification and propagation of uncertainty. It does not imply that we have collections of data.



## What's "distributed"?

Difference between distribution of probability and distribution of (a collection of) data.



## Distributions of probability

### Representations

* Density function

* Histogram

* Scatter plot

Behaviour of representations under transformations of data.



## Summaries of distributions of probability

### Location

Median, mean

### Dispersion or range

Quantiles & quartiles, interquartile range, median absolute deviation, standard deviation, half-range

### Resolution

Differential entropy

### Behaviour of summaries under transformations of data and errors in data



## Outliers and out-of-population data

(Warnings against tail-cutting and similar nonsense-practices)



## Marginal and conditional distributions of probability



## Collecting and sampling data

### "Representative" samples

Size of minimal representative sample = (2^entropy)/precision

* _Exercise: data with 14 binary variates, 10000 samples_

### Unavoidable sampling biases

In high dimensions, all datasets are outliers.

Data splits and cross-validation cannot correct sampling biases



## Quirks and warnings about high-dimensional data





