project:
  type: book
  output-dir: docs
  resources:
    - "robots.txt"
#    - "datasets"
#    - "code"

strip-comments: true

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

number-depth: 2

callout-icon: false

date: last-modified
date-format: iso

book:
  bread-crumbs: false
  date: today
  date-format: iso
  open-graph: false
  favicon: favicon.png
  cover-image: ada511logo.png
  title: "ADA511 [0.3]{.small .grey} <br>Data Science and AI prototyping"
  author:
    - "P.G.L. Porta Mana [![ORCID](orcid_32x32.png){width=1em}](https://orcid.org/0000-0002-6070-0784) [{{< fa home >}}](https://portamana.org/)"
    - "S. Mæland [![ORCID](orcid_32x32.png){width=1em}](https://orcid.org/0000-0002-4652-4753)"
  # downloads: pdf
  reader-mode: true
  sidebar:
    # date-format: iso
    # date: 02-02-1902
    title: "ADA511 [0.3]{.small .grey}<br>[{{< meta date >}}]{.small .grey}<br>[ ![CC BY-SA 4.0](cc_by_sa.png){width=3em} [licence]{.small .grey}](http://creativecommons.org/licenses/by-sa/4.0)<br>"
    logo: ada511logo8_small.png
    author:
      - name: P.G.L. Porta Mana
        orcid: 0000-0002-6070-0784
      - name: S. Mæland
        orcid: 0000-0002-4652-4753
    style: "docked"
    collapse-level: 3
  # search:
  #   location: navbar
  #   type: overlay
  chapters:
    - index.qmd
    - preface.qmd

    - part: "[**An invitation**]{.lightblue}"
      chapters:
        - intro.qmd
        - framework.qmd
        - basic_decisions.qmd
        - connection-1-ML.qmd
    - part: "[**Inference I**]{.green}"
      chapters:
        - inference.qmd
        - sentences.qmd
        - truth_inference.qmd
        - probability_inference.qmd
        - derived_rules.qmd
        - monty.qmd
        - connection-2-ML.qmd
    - part: "[**Data I**]{.yellow}"
      chapters:
        - quantities_types.qmd
        - quantities_types_multi.qmd

    - part: "[**Inference II**]{.green}"
      chapters:
        - probability_distributions.qmd
        - joint_probability.qmd
        - marginal_probability.qmd
        - conditional_probability.qmd
        - conditional_summary.qmd
        - information.qmd
        - connection-3-ML.qmd

    - part: "[**Data II**]{.yellow}"
      chapters:
        - populations_variates.qmd
        - statistics.qmd
        - subpopulations.qmd
        - samples.qmd

    - part: "[**Machine learning**]{.midgrey}"
      chapters:
        - machine_learning_overview.qmd
        # - decision_trees.qmd
        - neural_networks.qmd
        - llms.qmd
    - part: "[**Inference III**]{.green}"
      chapters:
        - beyond-ML.qmd
        - exchangeable_probabilities.qmd
        - inference_from_freqs.qmd
        - inference_about_freqs.qmd
        - summary_formulae.qmd
    - part: "[**A prototype Optimal Predictor Machine**]{.red}"
      chapters:
        - dirichlet-mixture.qmd
        - code_design.qmd
        - prototype_code.qmd
        - example_opm1.qmd
#        - OPM_application_nominal.qmd

    - part: "[**Decision-making**]{.blue}"
      chapters:
        - utilities.qmd
        - making_decisions.qmd
        - example_opm2.qmd
    - part: "[**Further connections with present-day machine-learning**]{.midgrey}"
      chapters:
        - limitations_ML.qmd
        - utilities_evaluation.qmd
    - part: "[**Conclusion**]{.lightblue}"
      chapters:
        - whither.qmd
        - bibliography.qmd
        - thanks.qmd
    - references.qmd
#    - __old-connection-3-ML.qmd



# bibliography: [portamanabib.bib, ADA511.bib]

format:
  html:
    # self-contained-math: true
    # embed-resources: true
    theme: flatly
    link-external-icon: false
    link-external-newwindow: true
    ## flatly journal litera simplex
    # mainfont: "DejaVu Sans"
    # monofont: "DejaVu Sans Mono"
    css: ada511styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    email-obfuscation: references
    # include-in-header: mathjax.html
    # sidebar:
    #   date-format: iso
    #   date: last-modified
    #   title: "ADA511 [0.2]{.small .grey} <br>Data science and data-driven engineering <br>updated {{< meta date >}}"
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   include-in-header:
  #     - text:
  #         \usepackage{mathtools}

filters:
  - mathpunctuation.lua
#  - center-images.lua

  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
  #   papersize: a4
  #   header-includes:
  #   - \usepackage{mathtools}
  #   - \usepackage[normalem]{ulem}

execute:
  freeze: auto
  # keep-ipynb: true
