# Multivariate and complex data types {#sec-data-types-multi}
{{< include macros.qmd >}}


### Other complex types

The types of quantities listed so far are all, in a certain sense,  one-dimensional.

Some complex quantities can be seen simply as collections of quantities of the types listed above, so their analysis and their main properties reduces somehow to the ones already discussed. For example, data about a customer may consist of the collection of two quantities *name*, *age*. The first is a nominal quantity, the second an interval one. The combined quantity "name-age" can be dealt with by considering the two quantities separately.

But there are many quantities whose sets of possible values have particular mathematical properties and operations that cannot be obtained by simply gathering together quantities of a one-dimensional type.
Examples are quantities related to functions, colours, images, audio, video, graphs. For such types of complex quantities it is often important to be able to say whether two values are "close" to each other or "far away". This leads to the introduction of *metrics* and other mathematical structures on the sets of values. The metrics may also depend on the particular purpose the quantity is used for.

Some of these types of complex quantities will be discussed on a case-by-case basis.


