# Data and information
{{< include macros.qmd >}}

## Quantities

Most decisions and inferences in engineering and data science involve quantities or entities with some kind of mathematical properties: they can be expressed by a number or -- think of images or network graphs -- by collections of numbers. The sentences that appear in decision-making and inferences are therefore often of the kind "the quantity $X$ was measured to have value $x$". We commonly refer to these values as "data".

Data come in many different kinds, with different properties. Some statements only make sense with particular kinds of data. We therefore pay a quick visit to the data zoo, emphasizing aspects that are important for inference and decision-making.

We shall speak of [**quantities**]{.blue}, denoting them by letters such as $X$. A quantity has a value that must belong to a given set called the [**domain**]{.blue} of that quantity.

Examples of quantities:

1. The distance between two objects in the Solar System at a specific time. The domain could be, say, all values from $0\,\mathrm{m}$ to $6\cdot10^{12}\,\mathrm{m}$ ([Pluto](https://solarsystem.nasa.gov/planets/dwarf-planets/pluto)'s average orbital distance).

1. The number of total views of some online video (at a specific time), with a domain, say, from 0 to 20 billions.

1. The force on an object (at a specific time and place). The domain could be, say, 3D vectors with components in $[-100\,\mathrm{N},\,+100\,\mathrm{N}]$.

1. The image taken by a camera. The domain could be all possible combinations of values in $[0,1]$ over three $1280\times 720$ grids (one grid per basic colour).

1. The degree of satisfaction in a customer survey, with five possible values `Not at all satisfied`, `Slightly satisfied`, `Moderately satisfied`, `Very satisfied`, `Extremely satisfied`.

1. The graph representing a social network, with domain consisting of all possible graphs with $0$ to $10000$ nodes and all possible combinations of links between the nodes.

1. The relationship between the input voltage and output current of an electric component. The domain could be all possible continuous curves from $[0\,\mathrm{V}, 10\,\mathrm{V}]$ to $[0\,\mathrm{A}, 1\,\mathrm{A}]$.

1. A 1-minute audio track recorded by a device with a sampling frequency of 48 kHz. The domain could be all possible 2 880 000 values in $[0,1]$.

1. The subject of an image, with domain of three possible values `cat`, `dog`, `something else`.

1. The [roll, pitch, yaw](https://www.grc.nasa.gov/www/k-12/rocket/rotations.html) of a rocket (at a specific time and place), with domain $(-180°,+180°]\times(-90°,+90°]\times(-180°,+180°]$.

We take it for granted that a quantity does have one value, and one value only (even if the value itself can consist of, say, several numbers).


## Types of quantities

### Nominal

A [**nominal**]{.blue} or [**categorical**]{.blue} quantity has a domain with a discrete (usually finite) number of values. The values [*are not related by any mathematical property*]{.blue}, and [*do not have any specific order*]{.blue} (at least not a priori).

This means that it does not make sense to say, for instance, that some value is "twice" or "1.5 times" another, or "larger" or "later" than another one. Nor does it make sense to "add" two quantities. In particular, [*there is no notion of average for a nominal quantity*]{.blue}.

An example is the possible breeds of a dog, or the characters of a film.

It is of course possible to represent the values of a nominal quantity with numbers; say `1` for `Dachshund`, `2` for `Labrador`, `3` for `Dalmatian`, and so on. But that doesn't mean that "`Dalmatian`${}-{}$`Labrador`${}={}$`Labrador`${}-{}$`Dachshund`" or similar nonsense.



### Ordinal

An [**ordinal**]{.blue} quantity has a domain with a discrete (usually finite) number of values. The values [*are not related by any mathematical property*]{.blue}, but [*do have a specific order*]{.blue}.

This means that it does not make sense to say that some value is "twice" or "1.5 times" another, and we cannot "add" two values. But it does make sense to say, for any two values, which one has higher rank; for example "stronger", or "later", and similar. Also in this case [*there is no notion of average for an ordinal quantity*]{.blue}.

An example would be a [pain-intensity scale](https://doi.org/10.1016/j.jpainsymman.2004.08.007): a patient can say whether a pain is more severe than another, but it isn't clear what a pain "twice as severe" as another would mean (although there's a lot of research  on  more precise quantification of pain). Another example could be the "strength of friendship" in a social network: we can say that we have a  "stronger friendship" with a person than with another; but it doesn't make sense to say that we are "four times stronger friends".

Also for ordinal quantities it is possible to represent the values with numbers. In this case the numbers can reflect the *order* of the values. But it's important to keep in mind that differences or averages of such numbers wouldn't make sense. Unfortunately the use of numbers can be deceptive in this regard. A less deceptive possibility is to represent ordered values by alphabet letters, for example.

### Binary

A [**binary**]{.blue} or [**dichotomous**]{.blue} quantity has only two possible values. Although it is really a special case of a nominal or ordinal quantity, the fact of having only two values lends it some special properties in inference problems. This is why we list it separately from others.

Obviously it doesn't make much sense to speak of the difference or average of the two values; and their ranking is trivial even if it makes sense.

There's an abundance of examples of binary quantities: yes/no answers, presence/absence of something, and so on.

### Interval

An [**interval**]{.blue} quantity has a domain that can be discrete or continuous. The values [*do admit some mathematical operations*]{.blue}, at least *convex combination* and *subtraction*. They also admit an ordering.

This means that we can say whether the interval or "distance" between a pair of values is the same, or larger, or smaller than the interval between another pair. For this reason we can also say whether a value is larger than another. We can also take the *convex combination* of several values, which means we can take a weighted sum of them. Note that simple *addition* of values may still be meaningless, though.

Owing to these mathematical properties, [**it does make sense to speak of the average for an interval quantity**]{.blue}.

The number of electronic components produced in a year by an assembly line is an example of a discrete interval quantity. The power output of a nuclear plant at a given time is an example of a continuous one.

It is also possible to speak of *ratio* quantities, which are a special case of interval quantities, but we won't have use of this distinction in the present notes.

### Other complex types

The types of quantities listed so far are all, in a certain sense,  one-dimensional.

Some complex quantities are simply collections of quantities of the types listed above, so their analysis and their main properties reduces somehow to the ones already discussed. For example, data about a customer may consist of the collection of two quantities *name*, *age*. The first is a nominal quantity, the second an interval one. The combined quantity "name-age" can be dealt with by considering the two quantities separately.

But there are many quantities whose sets of possible values have particular mathematical properties and operations that cannot be obtained by simply gathering together quantities of a one-dimensional type.
Examples are quantities related to functions, colours, images, audio, video, graphs. For such types of complex quantities it is often important to be able to say whether two values are "close" to each other or "far away". This leads to the introduction of *metrics* and other mathematical structures on the sets of values. The metrics may also depend on the particular purpose the quantity is used for.

Some of these types of complex quantities will be discussed on a case-by-case basis.

:::{.callout-caution}
## {{< fa user-edit >}} Exercises
- For each example at the beginning of the present section, determine the type of quantity.

- For each type of quantity discussed above, find two more concrete examples of that type.
:::

### Type is context-dependent

The type of a quantity is not only determined by its mathematical properties, but also by its use in each specific problem. A quantity of a more complex type can be treated as a simpler type if needed, but not vice versa. For instance, the response time of some device is in principle an interval quantity; but in a specific situation we could simply label its values as `slow`, `medium`, `fast`, thus making it an ordinal quantity.

@@ TODO: add examples for image spaces


## Other attributes of quantities

It is useful to consider other aspects of quantities that are not tied to a specific quantity type. These aspects can be important when drawing inferences about a quantity.

### Discrete vs continuous

Nominal and ordinal quantities have discrete domains. The domain of an interval quantity can be discrete or continuous. In practice all domains are discrete, since we cannot give values with infinite precision. In a modern computer, for example, a real number can "only" take on $2^{64} \approx 20 000 000 000 000 000 000$ possible values. In many situations the available precision is so high that we can really consider the quantity as continuous and use the mathematics of continuous sets -- derivation, integration, and so on -- to our advantage.

@@ TODO comment on repetition

### Finite vs infinite

The domain of a discrete quantity can have a finite or (at least in theory) an infinite number of possible values. For example, the number of times a link on a webpage can be clicked is in principle infinite. In some inference and decision-making problems it may be necessary to find a concrete finite maximum number for a quantity that is in principle infinite.

:::{.callout-caution}
## {{< fa user-edit >}} Exercises
If you had to set a maximum number of times a web link can be clicked, which number would you choose? Try to find a reasonable number, considering factors such as how fast a person can repeatedly click on a link, how long can a website (or the Earth?) last, and how many people can live in such an extent of time.
:::

### Bounded vs unbounded

Ordinal and interval quantities may have domains with no minimum value, or no maximum value, or neither. Typical names for these situations are *maximum-bounded* or *right-bounded*, *left-bounded*, *unbounded*, and so on. A domain can be infinite and yet bounded: consider the numbers in the range $[0,1]$,

### Rounded

A continuous interval quantity may be rounded, owing to the way it's measured. In this case the quantity could be considered discrete rather than continuous. Rounding can impact the way we do inferences about such a quantity.

For instance, the age of a person, which is in principle a continuous quantity, could be rounded down to years or months. Suppose age can only have values between 0 and 120 years, and consider the following cases:

- The age is measured with the precision of a minute, and we have age data about 100 persons. In this case it's very improbable that two or more data values will be identical.

- The age is measured with the precision of a year, and we have age data about 5 persons. Also in this case it's improbable (bute less improbable than in the previous case) that two or more data values will be identical.

- The age is measured with the precision of a year, and we have age data about 1 000 000 persons. Clearly many data values must be identical in this case.

### Censored




### "Soft" data

* orders of magnitude

* physical bounds

## Data transformations

* log

* probit

* logit


