---
jupyter: ir
---

{{< include macros.qmd >}}
{{< include macros_populations_variates.qmd >}}

# The universal exchangeable-inference machine in action

Consider the following population, which we consider to be exchangeable:

- [*Units*: glass fragments collected at particularly defined crime scenes.]{.small}

- [*Variates*:]{.small}
    + [$\vRI$, ordinal, domain $\set{1,\dotsc,5}$: Refractive Index of the fragment]{.small}
    + [$\vNa$, ordinal, domain $\set{1,\dotsc,5}$: Natrium content of the fragment]{.small}
    + [$\vMg$, ordinal, domain $\set{1,\dotsc,5}$: Magnesium content of the fragment]{.small}
    + [$\vAl$, ordinal, domain $\set{1,\dotsc,5}$: Aluminium content of the fragment]{.small}
    + [$\vSi$, ordinal, domain $\set{1,\dotsc,5}$: Silicon content of the fragment]{.small}
    + [$\vK$, ordinal, domain $\set{1,\dotsc,5}$: Potassium content of the fragment]{.small}
    + [$\vCa$, ordinal, domain $\set{1,\dotsc,5}$: Calcium content of the fragment]{.small}
    + [$\vBa$, ordinal, domain $\set{1,\dotsc,5}$: Barium content of the fragment]{.small}
    + [$\vFe$, ordinal, domain $\set{1,\dotsc,5}$: Iron content of the fragment]{.small}
	+ [$\vType$, nominal, domain $\set{\cat{T1},\dots,\cat{T7}}$: Type or origin of the glass fragment]{.small}
	
	[The values for the $\vRI$ and content variates represent ranges of numeric values or percentages, which you can find in [this metadata file](datasets/glass_metadata-5_lev.csv). In the same file you also find the description of the glass types.]{.small}

We have a sample of 214 units from this population; their variate values are stored in [this data file](datasets/glass_data-5_lev.csv). Here are the first five:

| $\vRI$ | $\vNa$ | $\vMg$ | $\vAl$ | $\vSi$ | $\vK$ | $\vCa$ | $\vBa$ | $\vFe$ | $\vType$ |
|:------:|:------:|:------:|:------:|:------:|:-----:|:------:|:------:|:------:|:------:|
| 2      | 2      | 5      | 3      | 3      | 1     | 2      | 1      | 1      |$\cat{T2}$|
| 2      | 2      | 4      | 3      | 3      | 1     | 2      | 1      | 1      |$\cat{T2}$|
| 3      | 3      | 5      | 2      | 2      | 1     | 2      | 1      | 1      |$\cat{T1}$|
| 2      | 3      | 2      | 3      | 3      | 1     | 2      | 2      | 1      |$\cat{T4}$|
| 2      | 2      | 4      | 2      | 3      | 1     | 2      | 1      | 1      |$\cat{T1}$|
: {.sm}

\

Now we imagine to be an agent who wants to make inferences about the full population -- which also means fragments from *future* or *unsolved* crime scenes. The agent uses -- or is the embodiment of -- the universal exchangeable-inference machine.

### Load the machine

We load several `R` functions that draw inferences, calculate marginal and conditional probabilities, and plot them:

```{r}
source('code/universal_exch-inference_machine.R')
```



