# [Inference under exchangeability]{.green} {#sec-inference-freq}
{{< include macros.qmd >}}

We can finally derive a concrete way of drawing inferences in problems involving exchangeable populations. We shall approach the derivation in an intuitive way, in two steps.


## Inference when population frequencies are known {#sec-inference-known-freq}

Suppose we have a practically infinite statistical population with variate $X$ having a discrete and finite domain. For simplicity let's assume the domain consists in the integers $\set{1,2,\dotsc,K}$ (we can always rename the actual domain values so as to put them into correspondence with a set of integers).

An agent with state of knowledge $\yI$ needs to draw inferences about some units, given the values of other units, as in the examples of the previous [§ @sec-two-populations] and [chapter @sec-exchangeability].

Now we suppose that the agent additionally **knows the joint frequency distribution** for the variate $X$ in the population. We express this knowledge with the sentence $\vec{F}\mo\vec{f}$, where $\vec{f}$ is a $K$-tuple of numerical frequencies. We denote the frequencies of the values $1,2,\dotsc, K$ by $f_1, f_2, \dotsc, f_K$.

If someone gave you the frequencies above (their exact numerical values), and asked you your degree of belief that the variate for some unit, say unit #47, has value $2$, what would you answer?

This scenario has a very strong symmetry. A fraction $f_2$ of all the units have value $2$. Unit #47 could be one among those in this fraction, or one among those in the remaining\ \ $1-f_2$\ \ fraction. We are compelled to give probability $f_2$ that unit #47 has value $2$:

$$
\P(X_{47}\mo 2 \| \vec{F}\mo\vec{f} \and \yI) = f_2
$$

This is just one way of looking at this scenario. Alternative ways show similar symmetries, which lead to the same degree of belief.

More generally, the agent's degree of belief on some unit #$u$ to have value $i$, when the joint frequency distribution $f$ is known, must be

$$
\P(X_u \mo i \| \vec{F}\mo\vec{f} \and\yI) = f_i
$$

\

We can extend this reasoning to more than one unit. A crucial point here is that the population is practically infinite. If we know that the frequency of value $2$ is $f_2$, and then we observe a unit with that value, then we know that the total number of units having value $2$ has slightly decreased. In a practically infinite population, however, this decrease is negligible, so we can think of $f_2$ as remaining the same.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
Suppose the population is finite, with $N$ units. The *absolute* frequency ([§ @sec-freq-distribs]) of value $2$ is then $Nf_2$.

- Calculate the new absolute and relative frequencies of value $2$ after we remove one unit with that value.
- Calculate the difference between the previous and new frequency.
- Do the same calculations also for the other variate values ($1,3,\dotsc$).
:::

We therefore find that the agent's degree of belief on some unit #$u$ to have value $i$, and some other unit #$v$ to have value $j$, when the joint frequency distribution $f$ is known, must be

$$
\P(X_u \mo i \and X_v\mo j \| \vec{F}\mo\vec{f} \and\yI) = f_i \cdot f_j
$$

And so on for more units.

---


[@@ TODO **to be continued**]{.red}


