# Marginal and conditional probabilities
{{< include macros.qmd >}}

## Marginal probability distributions {#sec-marginal-probs}

In some situations an agent has the joint probability distribution for a joint quantity, but it needs the probability for one of the component quantities only, *irrespective of what the values for the other components might be*.

Consider for instance the joint probability for the next-patient arrival scenario of [table @tbl-urgent-arrival]. We may be interested in the probability that the next patient will need urgent care, *independently of how the patient gets to the hospital*. This probability can be found, as usual, by analysing the problem in terms of *sentences* and using the [basic rules of inference from ยง @sec-fundamental].

The sentence of interest is

$$
\pr{The next patient will require urgent care}
$$

which is equivalent to

$$
\pr{The next patient will require urgent care, and will arrive by ambulance, helicopter, or other means}
$$

This last sentence can be written in terms of `and` and `or` connectives:

$$
\begin{aligned}
&\pr{The next patient will require urgent care} \land{}
\\[1ex]
&\qquad\bigl(\pr{The next patient will arrive by ambulance} \lor {}
\\&\qquad\qquad
\pr{The next patient will arrive by helicopter} \lor {}
\\&\qquad\qquad
\pr{The next patient will arrive by other means}\bigr)
\end{aligned}
$$

which we can compactly write as

$$
\begin{aligned}
&\prq{urgent}\land
(\prq{ambulance} \lor \prq{helicopter} \lor \prq{other})
\\[1ex]
&\qquad{}=
(\prq{urgent}\land \prq{ambulance}) \lor
(\prq{urgent}\land \prq{helicopter}) \lor
(\prq{urgent}\land \prq{other})
\end{aligned}
$$

where the second, equivalent form comes from the [derived rules of Boolean algebra of ยง @sec-boolean].

The last sentence is an `or` of mutually exclusive sentences. Its probability is therefore given by the `or` rule:

$$
\begin{aligned}
&\P\bigl[
(\prq{urgent}\land \prq{ambulance}) \lor
(\prq{urgent}\land \prq{helicopter}) \lor
(\prq{urgent}\land \prq{other})
\| \yi[H] \bigr]
\\[1ex]
&\qquad{}=
\P(\prq{urgent}\land \prq{ambulance}\| \yi[H] ) +
\P(\prq{urgent}\land \prq{ambulance}\| \yi[H] ) +
\P(\prq{urgent}\land \prq{other}\| \yi[H] )
\end{aligned}
$$

The probability for a value of the urgency quantity, independently of the value of the arrival-means quantity, can be found by summing all joint probabilities with all possible arrival-means values. Using the $\sum$-notation we can write
<!-- $$ -->
<!-- \P(\prq{urgent} \| \yi[H]) = -->
<!-- \sum_{A} -->
<!-- \P(\prq{urgent}, A\mo a \| \yi[H]) -->
<!-- $$ -->

$$
\P(\prq{urgent} \| \yi[H]) =
\sum_{\mathclap{a=\prq{ambulance}}}^{\mathclap{\prq{other}}}
\P(\prq{urgent}, A\mo a \| \yi[H])
$$


This is called a [**marginal probability**]{.blue}.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
Using the values from [table @tbl-urgent-arrival], calculate:

- the marginal probability that the next patient will need urgent care
- the marginal probability that the next patient will arrive by helicopter
:::

Considering now a more abstract case for a bivariate quantity with component quantities $X$ and $Y$, the probability for a specific value of $X$, conditional on some information $\yI$ and  irrespective of what the value of $Y$ might be, would be given by

$$
\P(X\mo x\| \yI) = \sum_{y} \P(Y\mo y, X\mo x \| \yI)
$$

You may notice the similarity with the expression for a *combined probability* from [ยง @sec-combined-probs]. Indeed a marginal probability is just a special case of a combined probability: we are combining all probabilities that exhaust the possibilities for the quantity $Y$.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise: test your understanding

Using again the values from [table @tbl-urgent-arrival], calculate the probability that *the next patient will need urgent care and will arrive either by ambulance or by helicopter*.
:::

\


## Conditional probability distributions {#sec-conditional-probs}

A joint probability distribution quantifies an agent's uncertainty about all the quantities that compose a joint quantity. This means that in general the agent has no sure certainty about any of them (there are of course special cases where probabilities can be $0$ or $1$, but they are not the general case). Suppose that the agent has a joint probability for the quantities $X$ and $Y$, conditional on a state of knowledge $\yI$:

$$ \P(X\mo x,Y\mo y \|\yI) $$

<!-- :::{.callout-warning} -->
<!-- ## -->
<!-- {{< fa exclamation-circle >}} Always keep in mind that these are just convenient shorthands for -->
<!-- $$ -->
<!-- \P(\pr{The quantity \(X\) has value \(x\)} \land  -->
<!-- \pr{The quantity \(Y\) has value \(y\)} -->
<!-- \| \yI) -->
<!-- $$ -->
<!-- ::: -->

Now consider these two situations:

1. the agent acquires knowledge that $X$ has true value $x$, so its state of knowledge has changed;

2. for inference purposes, the agents needs to *hypothetically* assume that the quantity $X$ has value $x$ (even if that might not be the case in reality);

and, in either situation, the agent needs the probability that $Y$ has value $y$. This probability is written, in either situation as

$$
\P(Y\mo y \| X\mo x, \yI)
$$

It is usually called a [**conditional probability**]{.blue}. It is somewhat a misnomer, because *all* probabilities are conditional on something. The implicit understanding here is that *new* information has been added to the conditional with respect to some base state of knowledge.

What is the numerical value of the conditional probability above? We simply use the `and`-rule:

$$
\P(Y\mo y \| X\mo x, \yI) =
\frac{\P(X\mo x,Y\mo y \|\yI)}{\P(X\mo x \| \yI)}
$$

The denominator is the *marginal probability* for $X$, which can also be calculated from the joint distribution as discussed in [ยง @sec-marginal-probs]:

$$
\P(X\mo x \| \yI) = \sum_{y} \P(Y\mo y, X\mo x \|\yI)
$$

We can thus rewrite the conditional probability as

$$
\P(Y\mo y \| X\mo x, \yI) =
\frac{\P(Y\mo y, X\mo x \|\yI)}{\sum_{y} \P(Y\mo y, X\mo x \|\yI)}
$$

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
Consider the next-patient problem with the joint probability of [table @tbl-urgent-arrival]:

1. Calculate the probability that the next patient needs urgent care, knowing that the patient will arrive by helicopter.

2. Compare the conditional probability you just found with the *marginal* probability that the next patient needs urgent care, independently of transportation means (calculated in a previous exercise). Which is higher? Why?

3. Calculate the probability that the next patient arrives by helicopter, knowing that the patient will need urgent care.

4. Compare the conditional probability from 3. with that from 1. Why are they so different? Why is the probability "$\prq{helicopter}\|\prq{urgent}$" so low, when "$\prq{urgent}\|\prq{helicopter}$" is so high instead? find an intuitive explanation.
:::


## The importance of marginal distributions for drawing inferences

@@ TODO
