# Multivariate probability distributions
{{< include macros.qmd >}}

So far we have considered  probability distributions for quantities of a basic (nominal, ordinal, binary, interval) type. These distributions have a sort of one-dimensional character and can be represented by ordinary histograms, line plots, and scatter plots. We now consider probability distributions for multivariate quantities.

[*(Make sure you're familiar with [ยง @sec-data-types-multi] before you begin.)*]{.small style="color:#EE6677;"}

## Joint probability distributions

A multivariate quantity, as discussed in [ยง  @sec-data-multiv], is just a collection or set of quantities of basic types. Saying that a multivariate quantity has a particular value means that each basic component quantity has a particular value in its specific domain. This is expressed by an `and` of sentences.

Consider for instance the multivariate quantity $X$ consisting of the age $\color[RGB]{102,204,238}A$ and sex $\color[RGB]{34,136,51}S$ of a specific person. The fact that $X$ has a particular value is expressed by a composite sentence such as
$$
\pr{The person's age is 25 years and the sex is female}
$$
which we can compactly write with an `and`:
$$
({\color[RGB]{102,204,238}A\mo 25\,\mathrm{y}}) \land ({\color[RGB]{34,136,51}S\mo\mathrm{F}})
$$
All the possible composite sentences of this kind are *mutually exclusive* and *exhaustive*.

An agent's uncertainty about $X$'s true value is therefore represented by a probability distribution over all `and`-ed sentences of this kind, representing all possible joint values:
$$
\P\bigl[({\color[RGB]{102,204,238}A \mo 25\,\mathrm{y}}) \land ({\color[RGB]{34,136,51}S\mo\mathrm{F}}) \| \yI\bigr] \ , \qquad
\P\bigl[({\color[RGB]{102,204,238}A \mo 31\,\mathrm{y}}) \land ({\color[RGB]{34,136,51}S\mo\mathrm{M}}) \| \yI\bigr] \ , \qquad
\dotsc
$$
where $\yI$ is the agent's state of knowledge, and the probabilities sum up to one. We call this a [**multivariate**]{.blue} or [**joint probability distribution**]{.blue}. Usually these probabilities are written in much abbreviated form, and the $\land$ is represented by a comma; for instance
$$
\P({\color[RGB]{102,204,238}25}, {\color[RGB]{34,136,51}\mathrm{F}} \| \yI) \ , \quad
\P({\color[RGB]{102,204,238}31}, {\color[RGB]{34,136,51}\mathrm{M}} \| \yI) \ , \quad
\dotsc
$$


## Representation of joint probability distributions

There is a wide variety of ways of representing multivariate probability distributions, and new ways are invented (and rediscovered) all the time. In some cases, especially when the quantity has more than three component quantities, it can become impossible to graphically represent the probability distribution in a faithful way. Therefore one often tries to represent only some aspects or features of interest from the full distribution. Whenever you see a plot of a multivariate probability distribution, you should carefully read what the plot shows and how it was made. Here we only illustrate some examples and ideas for representations.

### Tables

When a quantity is *bi*variate and its two component quantities are both discrete and finite, the joint probabilities can be reported as a table.

@@ TODO also contingency tables

### Multi-line plots

@@ TODO for discrete-continuous distributions


### Surface plots

### Scatter plots

@@ TODO work also for 3D




