# Populations & exchangeability
{{< include macros.qmd >}}

To solve *any* inference problem, or to design an AI agent for solving an inference problem, all we have to do in principle is to repeatedly use the [fundamental laws of inference of § @sec-fundamental].

In many cases an in-principle application of the inference laws is computationally impossible, however. Approximate calculations and premises are then used, sometimes quite drastic. The approximation used depends on the nature of the inference problem. This is why inference problems are often classified in one way or another, and different solution recipes are presented for the different classes.

For a data-science engineer it is important to keep in mind that these recipes are only approximations, and to keep the principled solution always in sight. Technological advances continually allow us to make computations that were previously impossible -- think of "quantum computers" these days. A truly optimal in-principle solution, preferable to a sub-optimal approximation, can suddenly become accessible -- to those who know it.

\

We shall now introduce a very rough distinction between two very broad classes of inference problems, and then study the principled solution of one of them, and approximations to this solution.

## Exchangeable vs non-exchangeable inferences {#sec-exchangeability}

Consider these two inference problems:

1. Assessing the value that a particular investment fund will have in 100 days from now, given the course of that fund in the past 3650 days (10 years).

2. Assessing the failure status of the 100th electronic component, counting from now, out of an assembly line, given the failure status of the last 1000 electronic components already out of the same assembly line.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
Discuss:

- Which of the two inferences above seems more difficult?
- Why? Explore and discuss all factors that could make one inference more difficult than the other.
- Which differences and similarities do you find between the two inferences?
- Answer the same questions, considering two inference problems that are similar but "backwards in time":

    1b. Assessing the value that a particular investment fund had in 3750 days ago, given the course of that fund in the past 3650 days.

    2b. Assessing the failure status of the past 1100th electronic component from an assembly line, given the failure status of the last 1000 electronic components already out of the same assembly line.
:::

The first inference problem seems, and notoriously is, more difficult than the second. -- But why? Let's try to find some concrete and, if possible, generalizable aspect that can account for this difference in difficulty.

The time factor of the first inference could be a candidate. The first inference is in fact often categorized as a "[time-series analysis](https://www.abs.gov.au/statistics/understanding-statistics/statistical-terms-and-concepts/time-series-data)", because it involves changes in time. Yet, time cannot be the fundamental aspect that makes it more difficult than the second, because the second inference involves time as well: we want to assess the failure status of a future component, given the status of past ones.

An inference is not difficult or easy in itself, but only in relation to the information from which an agent draws it. So let's focus on the *conditionals* of the two inferences. The conditionals have different amounts of data. But this cannot be the aspects that accounts for the greater difficult of the first inference, because its conditional (course of the fund in 3650 days) has actually more data than that of the second (failure status of 1000 components).

In fact, we feel that 3650 days of a fund's course are somehow less informative to forecast is value in 100 days, than the failure status of 1000 components is for forecasting the failure of the 100th component from now.

To see the core of the difference, imagine that someone proposes the following exchange of knowns and unknowns in the two inferences, as schematized in the side figure:

:::{.column-margin}
![Illustration of the inference exchange. "[✓]{.blue}": known, "[?]{.purple}": unknown.](exchange_illustrationv){width=40%}
:::

1. Instead of assessing the value (unknown) of the fund in 100 days, given the values (known) in the past 3650 days, you can assess the value (unknown) in one of the 3650 days, given the values (known) in the remaining 3649 days and in the day 100 in the future.

2. Instead of assessing the failure status (unknown) of the 100th component from now, given the status (known) of the past 1000 components, you can assess the status (unknown) of one of the 1000 components, given the status (known) of the remaining 999 and of the 100th component from now.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
Discuss:

- Does the exchanged inference seem less difficult than the original one, in the first inference problem? And in the second?
- Why?
:::

In the case of the inference problem about the fund value, the exchanged inference seems much easier. Because we expect known fund values closer to the unknown one to be more informative. In the case of the inference problem about the failure status, the exchanged inference might be slightly easier, but still roughly on the same level of difficulty and the original one.

An inference which remains basically the same if a quantity in the *proposal* is exchanged with a quantity in the *conditional* is called [**exchangeable**]{.blue}.

















