# [References]{.lightblue} {.unnumbered}
{{< include macros.qmd >}}

:::{.blue}

*Believe nothing, O monks, merely because you have been told it, or because it is traditional, or because you yourselves have imagined it. Do not believe what your teacher tells you merely out of respect for the teacher.*
\ \ \ \ [(Attributed to Gautama Buddha)]{style="text-align:right;font-size:75%"}

\

*But in the natural sciences, whose conclusions are true and necessary and have nothing to do with human will, one must take care not to place oneself in the defense of error; for here a thousand Demostheneses and a thousand Aristotles would be left in the lurch by every mediocre wit who happened to hit upon the truth for himself.*
\ \ \ \ [([Galileo Galilei](references.html))]{style="text-align:right;font-size:75%"}
:::


The notions, ideas, and rules that you have learned in this course have been presented in such a way as to appear plausible and intuitively understandable. In some places we gave sketch of proofs.

But that is not enough.

A "data mechanic" (see [preface](preface.html)) might be excused for using incorrect formulae, and might simply say "this is the procedure I was taught". You instead, as a data *engineer* and data *scientist*, have the duty to check the validity of the theory and principles that you use in developing new algorithms, code, solutions.

In particular, you cannot accept theories or methods simply because

:::{.red}
- {{< fa thumbs-down >}}\ \ they are commonly used, or used by the majority of some community;

- {{< fa thumbs-down >}}\ \ some "authority" or known scientist says they are correct.
:::

In fact, *Science began when the two criteria above were discarded as not valid*. Galileo's quote above says this very explicitly. Imagine if Einstein had said "all scientists see no problem with the notion of simultaneity, so it must be correct", or "great scientists like Maxwell or Poincaré did not see any problem with the notion of simultaneity, so it must be correct". There is no scientific progress with this kind of reasoning.

Instead, the only two scientific criteria you have to decide on the validity of a method or theory are

:::{.green}
- {{< fa thumbs-up >}}\ \ logical proof,

- {{< fa thumbs-up >}}\ \ experimental corroboration.
:::

which you must do as much as possible *by yourself*. The more verification you delegate to others, to majority or "authority", the less you are doing science.

\

For this reason you have, at some point, go and check for yourself the validity of what you've learned in this course. You might in fact find out that something was not correct! Then you'll correct it and make science advance. Throughout the course We have given references where many proofs can be found. Here are some final references containing the main proofs of what you have learned here; you should check and validate them at some point.

\
\

- R. A. Briggs (2014/2019): [*Normative Theories of Rational Choice: Expected Utility*](https://plato.stanford.edu/archives/fall2019/entries/rationality-normative-utility).

- T. M. Cover, J. A. Thomas (1991/2006): [*Elements of Information Theory*](https://doi.org/10.1002/0471200611).

- R. T. Cox (1946): [*Probability, Frequency and Reasonable Expectation*](https://doi.org/10.1119/1.1990764).

- M. Cox, A. O'Hagan (2022): [*Meaningful expression of uncertainty in measurement*](https://doi.org/10.1007/s00769-021-01485-5).

- R. M. Dawes, T. L. Smith (1985): *Attitude and opinion measurement*, pp. 509--566 in G. Lindzey, E. Aronson: [*Handbook of Social Psychology. Vol. I: Theory and Method*](https://casbs.stanford.edu/handbook-social-psychology).

- P. Diaconis, S. Holmes, R. Montgomery (2007): [*Dynamical Bias in the Coin Toss*](https://doi.org/10.1137/S0036144504446436).

- C. Drummond, R. C. Holte (2005): [*Severe Class Imbalance: Why Better Algorithms Aren't the Answer*](https://webdocs.cs.ualberta.ca/~holte/Publications/ecml05.pdf).

- K. Dyrland, A. S. Lundervold, P.G.L. Porta Mana (2022): [*Does the evaluation stand up to evaluation?: A first-principle approach to the evaluation of classifiers*](https://doi.org/10.31219/osf.io/7rz8t).

- E. Eells (1982/2016): [*Rational Decision and Causality*](https://doi.org/10.1017/CBO9781316534823).

- N. Fenton, M. Neil (2019): [*Risk Assessment and Decision Analysis with Bayesian Networks*](https://doi.org/10.1201/b21982).

- G. Galilei (1632/1967): [*Dialogue concerning the two chief world systems -- Ptolemaic & Copernican*](https://www.ucpress.edu/books/dialogue-concerning-the-two-chief-world-systems-ptolemaic-and-copernican-second-revised-edition/)

- S. J. Gould (1985/2013): [*The Median Isn't the Message*](https://doi.org/10.1001/virtualmentor.2013.15.1.mnar1-1301).

- P. C. Gregory (2005): [*Bayesian Logical Data Analysis for the Physical Sciences*](https://doi.org/10.1017/CBO9780511791277).

- T. Hailperin (1965): [*Best Possible Inequalities for the Probability of a Logical Function of Events*](https://doi.org/10.1080/00029890.1965.11970533).

- T. Hailperin (1996): [*Sentential Probability Logic: Origins, Development, Current Status, and Technical Applications*](https://archive.org/details/hailperin1996-Sentential_probability_logic).

- R. Hastie, R. M. Dawes (2001/2010): [*Rational Choice in an Uncertain World: The Psychology of Judgment and Decision Making*](https://uk.sagepub.com/en-gb/eur/rational-choice-in-an-uncertain-world/book231783).

- D. Heath, W. Sudderth (1976): [*De Finetti's Theorem on Exchangeable Variables*](https://doi.org/10.1080/00031305.1976.10479175).

- M. Ingham (2012): [*No More Band-Aids: Integrating FM into the Onboard Execution Architecture*](https://github.com/pglpm/ADA511/raw/master/literature/ingham2012.pdf).

- E. T. Jaynes (1994/2003): [*Probability Theory: The Logic of Science*](https://archive.org/details/XQUHIUXHIQUHIQXUIHX2).

- R. L. Keeney, H. Raiffa (1976/1993): [*Decisions with Multiple Objectives: Preferences and Value Tradeoffs*](https://doi.org/10.1017/CBO9781139174084).

- W. Kruskal, F. Mosteller (1979): [*Representative Sampling, I: Non-scientific Literature*](https://doi.org/10.2307/1403202).

- D. V. Lindley (1971/1988): [*Making Decisions*](https://www.wiley.com/en-us/Making+Decisions%2C+2nd+Edition-p-x000008175).

- D. V. Lindley, M. R. Novick (1981): [*The role of exchangeability in inference*](https://doi.org/10.1214/aos/1176345331).

- D. J. C. MacKay (1995/2005): [*Information Theory, Inference, and Learning Algorithms*](https://www.inference.org.uk/itila/book.html).

- G. Malinas, J. Bigelow (2004/2016): [*Simpson's paradox*](https://plato.stanford.edu/archives/fall2016/entries/paradox-simpson/).

- C. E. Metz (1978):  [*Basic principles of ROC analysis*](https://doi.org/10.1016/S0001-2998(78)80014-2).

- D. G. Morrison (1967): [*On the consistency of preferences in Allais' paradox*](https://doi.org/10.1002/bs.3830120503).

- A. O'Hagan (1988): [*Probability: Methods and measurement*](https://doi.org/10.1007/978-94-009-1211-3).

- M. Ono, A. Nicholas, F. Alibay, J. Parrish (2015): [*SMART: A propositional logic-based trade analysis and risk assessment tool for a complex mission*](https://doi.org/10.1109/AERO.2015.7119021).

- H. Raiffa (1968/1970): [*Decision Analysis: Introductory Lectures on Choices under Uncertainty*](https://archive.org/details/decisionanalysis00raif).

- S. J. Russell, P. Norvig (1995/2022): [*Artificial Intelligence: A Modern Approach*](http://aima.cs.berkeley.edu/global-index.html).

- D. S. Sivia (1996/2006): [*Data Analysis: A Bayesian Tutorial*](https://doi.org/10.1093/oso/9780198568315.002.0001).

- H. C. Sox, M. C. Higgins, D. K. Owens (1988/2013): [*Medical Decision Making*](https://doi.org/10.1002/9781118341544).

- K. Steele, H. O. Stef{\'a}nsson (2015/2020): [*Decision Theory*](https://plato.stanford.edu/archives/win2020/entries/decision-theory).

- J. A. Swets, W. P. Tanner, Jr., T. G. Birdsall (1961): [*Decision processes in perception*](https://doi.org/10.1037/h0040547).

- B. C. Williams, M. D. Ingham, S. H. Chung, P. H. Elliott (2003): [*Model-based programming of intelligent embedded systems and robotic space explorers*](https://doi.org/10.1109/JPROC.2002.805828).

<!--  (): [**](https://doi.org/) -->

