# Data: use and communication

## Statements

What is "data"?

"Data" is often presented as numbers; but obviously it's more than that. I give you this number: "5". OK it's a number, but is it "data"? What is it about? what should you do with it? Instead, if I tell you: "_The number of lectures in this course is 5_", then we can say that I've given you data (even if it's actually false data). So "data" is not just numbers. A number is not "data" unless there's some verbal, non-numeric context associated with it -- even if this context is only implicitly understood.

Data can also be completely non-numeric. A clinician saying "_The patient has fully recovered from the disease_" (we imagine to know who's the patient and what was the disease) is giving us a piece of information that we could further use, for instance, to make prognoses about other, similar patients. The clinician's statement surely is "data". It is essentially non-numeric data, even if in some situations we can represent it as "1", say, while "0" would represent "not recovered".

From these two examples, and with some further thought, we realize that "data" -- and in general any piece of information or hypothesis -- can universally be represented and communicated by _statements_ , also called _sentences_ or _propositions_^[These terms are not equivalent in Logic, but we'll use them as synonyms here.]. In some cases we can summarize or represent such statements as numbers. But the numbers alone, by themselves, are not data.

In these notes we use the words "data" and "information" as synonyms. So our conclusion is that _information_ is represented by _statements_.


## Well-posed and ill-posed statements

We face problems when the statements that should convey information and data are not clear. Suppose that an electric-car model [consumes 150 Wh/km](https://ev-database.org/cheatsheet/energy-consumption-electric-car) and [has a range of 200 km](https://ev-database.org/cheatsheet/range-electric-car); a second car model consumes 250 Wh/km and has a range of 600 km. Someone says "I think the second model is better; what do you think?". It isn't clear how we should answer; what does "better" mean? If it refers to consumption, then the first car model is "better". If it refers to range, then the second model is "better". If it refers to a combination of these two characteristics, or to something else, then we simply can't answer. Here we have a problem with querying and giving data, because the statement underlying such query is not clear.

We say that such statement are **not well-posed**, or that they are **ill-posed**.

This may seem an obvious discussion to you. Yet you'd be surprised by how often unclear statements appear in scientific papers about data engineering! Not seldom we find discussions and disagreements that actually come from unclear underlying statements, that two parties interpret in different ways.

As a data engineer, you'll often have the upper hand if you are on the lookout for ill-posed statements. Whenever you face an important question, or you're given an important piece of information, or you must provide an important piece of information, _always take a little time to examine whether the question or information is actually well-posed_.

* _[TODO] Exercise: give actual paper to analyse_

