# Subpopulations
{{< include macros.qmd >}}
{{< include macros_statistics.qmd >}}


## Subpopulations {#sec-subpopulations}

When we have a statistical population with a joint variate, it is often of interest to focus on a subset of units that share the same value of a particular variate.

Consider for instance the following population, a modified version of the glass-forensics example:

- *units:* glass fragments (collected at specific locations)
- *variate:* the joint variate $(\vCa, \vSi, \vType)$ consisting of three simple variates:
	+ weight fraction of $\vCa$lcium in the fragment (ordinal variate), with three possible values `low`, `medium`, `high`
	+ weight fraction of $\vSi$licon in the fragment (ordinal variate), with three possible values `low`, `medium`, `high`
    + $\vType$ of glass fragment (nominal variate), with seven possible values `building_windows_float_processed`, `building_windows_non_float_processed`, `containers`, `tableware`, `headlamps`


| [unit]{.yellow}  |    $\vCa$  |    $\vSi$  |                                $\vType$  |
|:----------------:|:----------:|:----------:|:----------------------------------------:|
|    [1]{.yellow}  |     `low`  |    `high`  |                             `headlamps`  |
|    [2]{.yellow}  |     `low`  |  `medium`  |  `building_windows_non_float_processed`  |
|    [3]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
|    [4]{.yellow}  |  `medium`  |  `medium`  |      `building_windows_float_processed`  |
|    [5]{.yellow}  |     `low`  |  `medium`  |                             `headlamps`  |
|    [6]{.yellow}  |  `medium`  |  `medium`  |                            `containers`  |
|    [7]{.yellow}  |     `low`  |  `medium`  |  `building_windows_non_float_processed`  |
|    [8]{.yellow}  |     `low`  |    `high`  |                             `tableware`  |
|    [9]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
|   [10]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
: Glass fragments simplified {#tbl-glass-simple .sm}


Let's say we are interested only on those units that have the $\vType$ variate equal to `tableware`. Discarding all others we obtain a new, smaller population with four units:

| [unit]{.yellow}  |    $\vCa$  |    $\vSi$  |                 $\boldsymbol{\|}\vType$  |
|:----------------:|:----------:|:----------:|:----------------------------------------:|
|    [3]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
|    [8]{.yellow}  |     `low`  |    `high`  |                             `tableware`  |
|    [9]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
|   [10]{.yellow}  |  `medium`  |  `medium`  |                             `tableware`  |
: Selection according to $\vType\mo \cat{tableware}$ {#tbl-glass-tableware .sm}

were a bar "$\boldsymbol{\|}$" indicates the variate used for the selection.


As another example, we could be interested instead in those units that have both $\vCa$ *and* $\vSi$ variates equal to `medium`. We obtain a smaller population with five units:

| [unit]{.yellow}  |  $\boldsymbol{\|}\vCa$  |        $\boldsymbol{\|}\vSi$  |                                $\vType$  |
|:----------------:|:-----------------------:|:-----------------------------:|:----------------------------------------:|
|    [3]{.yellow}  |  `medium`               |  `medium`                     |                             `tableware`  |
|    [4]{.yellow}  |  `medium`               |  `medium`                     |      `building_windows_float_processed`  |
|    [6]{.yellow}  |  `medium`               |  `medium`                     |                            `containers`  |
|    [9]{.yellow}  |  `medium`               |  `medium`                     |                             `tableware`  |
|   [10]{.yellow}  |  `medium`               |  `medium`                     |                             `tableware`  |
: Selection according to $\vCa\mo \cat{medium}$ and $\vSi\mo \cat{medium}$ {#tbl-glass-ca-si-medium .sm}



Populations formed in this way are called [**subpopulations**]{.blue} of the original one. They are statistical populations in their own right. The notion of "subpopulation" is a relative notion. Any population can often be considered as a subpopulation of some larger population having additional variates.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise
- From the population of [table @tbl-glass-simple]:
    + Construct he *marginal* population with variate $\vCa$
    + Report the frequency distribution for the marginal population above (remember that $\vCa$ has *three* possible values)
    + Construct the subpopulation with variate $\vSi$ equal to `high`
    + Construct the subpopulation with variate $\vType$ equal to `headlamps` and the variate $\vSi$ equal to `medium`


*Check your understanding of the reasoning behind the notions of marginal population and subpopulation with this exercise:*

- From the population of [table @tbl-glass-simple], construct the subpopulation with variate $\vType$ equal to either `headlamps` *or* `tableware`.
:::



## Conditional frequencies {#sub-conditional-freqs}

Given a statistical population with joint variates ${\green X}, {\red Y}$ (and possibly others), we define the [**conditional frequency**]{.blue} of the value ${\red y}$ of  ${\red Y}$, given or "conditional on" the value ${\green x}$ of  ${\green X}$, as the frequency of the value ${\red y}$ in the subpopulation selected by ${\green X\mo x}$. This frequency is usually written

$$
f({\red Y\mo y} \| {\green X\mo x})
$$

where $f$ is the symbol for the joint frequency of the population.

Consider for instance the glass-fragment population of [table @tbl-glass-simple]. The conditional frequency of ${\red\vCa\mo \cat{low}}$ given ${\green\vType\mo \cat{tableware}}$ is the (marginal) frequency of $\vCa\mo \cat{low}$ in the subpopulation of [table @tbl-glass-tableware], from which we find

$$
f({\red \vCa\mo \cat{low}} \| {\green \vType\mo \cat{tableware}}) = \frac{1}{4}
$$

The collection of these conditional frequencies for all values of ${\red Y}$ constitutes the [conditional frequency distribution]{.blue} of ${\red Y}$ conditional on ${\green X\mo x}$. In our example this distribution has three conditional frequencies:

$$\begin{aligned}
&f({\red \vCa\mo \cat{low}} \| {\green \vType\mo \cat{tableware}}) = \frac{1}{4}
\\
&f({\red \vCa\mo \cat{medium}} \| {\green \vType\mo \cat{tableware}}) = \frac{3}{4}
\\
&f({\red \vCa\mo \cat{high}} \| {\green \vType\mo \cat{tableware}}) = 0
\end{aligned}$$

which sum up to $1$ as they should.

:::{.callout-warning}
## {{< fa exclamation-circle >}} Conditional on a *value* of a variate

It doesn't make sense to speak of the conditional frequency distribution of $Y$ "conditional [on $X$"]{.yellow}. Conditional frequencies and frequency distributions are always conditional on some value of a variate. If we consider all possible values of $Y$ *and* of $X$ we obtain a collection of frequencies that is *not* a distribution.
:::

A conditional frequency can be calculated as the ratio of a joint and a marginal frequencies, in a way analogous to conditional probabilities ([§ @sec-conditional-probs]):

$$
f({\red Y\mo y} \| {\green X\mo x}) =
\frac{f({\red Y\mo y}, {\green X\mo x})}{f({\green X\mo x})} =
\frac{f({\red Y\mo y}, {\green X\mo x})}{
\sum_{\red y} f({\red Y\mo y}, {\green X\mo x})}
$$


:::{.callout-caution}
## {{< fa user-edit >}} Exercises
Calculate the conditional frequency distributions corresponding to the subpopulations of tables [@tbl-glass-tableware] and [@tbl-glass-ca-si-medium]. For example, for [table @tbl-glass-tableware] this means calculating

$$\begin{aligned}
&f(\vCa\mo\cat{low}, \vSi\mo\cat{low} \| \vType\mo\cat{tableware})\ ,
\\
&f(\vCa\mo\cat{low}, \vSi\mo\cat{medium} \| \vType\mo\cat{tableware})\ ,
\\
&\dotsc\ ,
\\
&f(\vCa\mo\cat{high}, \vSi\mo\cat{high} \| \vType\mo\cat{tableware})
\end{aligned}$$
:::


## Associations

The analysis of subpopulations and conditional frequencies is important because it often reveals peculiar [*associations*]{.blue} among different variates and groups of variates. Let's illustrate what we mean with "association" -- a term that we'll use loosely, not with a strict technical definition -- with an example.

If we extract the subpopulation having variate $\vType$ equal to `headlamps` from the population of [table @tbl-glass-simple]:

| [unit]{.yellow}  |    $\vCa$  |    $\vSi$  |                 $\boldsymbol{\|}\vType$  |
|:----------------:|:----------:|:----------:|:----------------------------------------:|
|    [1]{.yellow}  |     `low`  |    `high`  |                             `headlamps`  |
|    [5]{.yellow}  |     `low`  |  `medium`  |                             `headlamps`  |
: Selection according to $\vType\mo \cat{headlamps}$ {#tbl-glass-headlamps .sm}

we notice that all units have variate $\vCa$ equal to `low`. In terms of conditional frequencies, this means

$$
\begin{aligned}
&f(\vCa\mo\cat{low} \| \vType\mo\cat{headlamps}) = 1
\\
&f(\vCa\mo\cat{medium} \| \vType\mo\cat{headlamps}) = 0
\\
&f(\vCa\mo\cat{high} \| \vType\mo\cat{headlamps}) = 0
\end{aligned}
$$

It is therefore impossible to observe other values of $\vCa$ in this new population.^[We are not claiming that this fact will be true if new units are considered; this important question will be discussed later.]

On the other hand, if we extract the subpopulation having variate $\vCa$ equal to `low` we obtain

| [unit]{.yellow}  |    $\boldsymbol{\|}\vCa$  |    $\vSi$  |                                $\vType$  |
|:----------------:|:-------------------------:|:----------:|:----------------------------------------:|
|    [1]{.yellow}  |     `low`                 |    `high`  |                             `headlamps`  |
|    [2]{.yellow}  |     `low`                 |  `medium`  |  `building_windows_non_float_processed`  |
|    [5]{.yellow}  |     `low`                 |  `medium`  |                             `headlamps`  |
|    [7]{.yellow}  |     `low`                 |  `medium`  |  `building_windows_non_float_processed`  |
|    [8]{.yellow}  |     `low`                 |    `high`  |                             `tableware`  |
: Selection according to $\vCa\mo \cat{low}$ {#tbl-glass-ca-low .sm}

with conditional frequencies such as

$$
\begin{aligned}
&f(\vType\mo\cat{headlamps} \| \vCa\mo\cat{low}) = \frac{2}{5}
\\
&f(\vType\mo\cat{tableware} \| \vCa\mo\cat{low}) = \frac{1}{5}
\end{aligned}
$$

and so on. The reverse is therefore *not* true: if $\vCa$ is equal to `low`, that does *not* mean that it's impossible to observe other $\vType$ values besides `headlamps`. Note especially how these probabilities differ:

$$
\begin{gathered}
f(\vCa\mo\cat{low} \| \vType\mo\cat{headlamps}) = 1
\\
f(\vType\mo\cat{headlamps} \| \vCa\mo\cat{low}) = \frac{2}{5}
\end{gathered}
$$


In the original population we have, figuratively speaking, the following interesting association:

$$
\vType\mo \cat{headlamps}\ \mathrel{\green\Rightarrow}\ 
\vCa\mo \cat{low}
\qquad\text{\small but}\qquad
\vCa\mo \cat{low}\  \mathrel{\red\nRightarrow}\ 
\vType\mo \cat{headlamps}
$$

This kind of associations is often useful. Suppose for instance that you are asked to pick a unit with $\vCa$ equal to `low` in the original population; but it's difficult to measure a unit's $\vCa$ value, while it's easy to measure its $\vType$ value. Then you could instead search for a unit having $\vType$ equal to `headlamps` (easier search), and you would be sure that the unit you found also has $\vCa$ equal to `low`.

\

The example above above, where some values of a variate completely exclude some values of another, is extreme. More often we find that there are small or large changes in the frequency distribution of some variate, depending on the subpopulation considered.

:::{.callout-caution}
## {{< fa user-edit >}} Exercise

- Calculate the (marginal) frequency distribution for the $\vCa$ variate for the glass-fragment population of [table @tbl-glass-simple], considering this variate to have values `low` and `medium` (so we disregard `high`). Is one value more frequent than the other?

- Calculate the frequency distribution for $\vCa$, conditional on $\vType\mo\cat{tableware}$ (see [table @tbl-glass-tableware]). How does this frequency distribution differ from the one calculated previously? Come up with possible ways to exploit this difference in concrete applications.
:::

### Associations can be very counter-intuitive

It is usually best to assess associations by explicitly calculating all relevant conditional frequencies, rather than jumping to intuitive conclusions after having examined just a few. Here's an example.

\

A statistical population of 80 units is defined as follows:

- *units:* reparations done by a repair company on a particular kind of electronic components, which is extremely delicate and usually very difficult to repair.

- a joint *variate*, consisting in three binary ones:
    + $\vLoc$ of the repair procedure, with values $\oonsite$ and $\oremote$;
	
    + repair $\vMet$, with values $\oold$ and $\onew$, representing a traditional reparation method and one introduced more recently;
	
	+ $\vOut$ of the repair procedure, with values $\osuccess$ and $\ofailure$.

The population data is stored in [this `csv` file](datasets/repair_data.csv).

**The repair company claims that, in this population, the $\onew$ repair method is more effective than the $\oold$.** Can back up their claims?:

:::{.callout-caution}
## {{< fa user-edit >}} Exercise

Use the population data from [this `csv` file](datasets/repair_data.csv). The calculations can be done with any tools you like.

- 1. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\onew$ (note that we are disregarding the $\vLoc$).

    2. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\oold$.

    3. Compare the two conditional frequency distributions above. Which of the two repair methods seems more effective?\
	Are the claims of the repair company justified?


- Now examine the reparations that have been done $\oonsite$.

    4. Before doing any calculations, what do you expect to find? should the $\onew$ repair method be more effective than the $\oold$ one, for onsite reparations?

    5. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\onew$ and $\vLoc\mo\oonsite$.
	
    6. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\oold$ and $\vLoc\mo\oonsite$.
	
	7. Compare the two conditional frequency distributions for this $\oonsite$ case. Which of the two repair methods seems more effective?\
	How do you explain this result in the light of what you found in step 3.?

- Now examine the reparations that have been done $\oremote$ly.

    8. Before doing any calculations, what do you expect to find? should the $\onew$ repair method be more effective than the $\oold$ one, for reparations done remotely?

    9. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\onew$ and $\vLoc\mo\oremote$.
	
    10. Calculate the frequency distribution of the $\vOut$ variate, conditional on $\vMet\mo\oold$ and $\vLoc\mo\oremote$.
	
	11. Compare the two conditional frequency distributions for this $\oremote$ case. Which of the two repair methods seems more effective?\
	How do you explain this result in the light of what you found in steps 3. and 7.?


- Summarize and explain all your findings.\
    Can the repair company claim that the $\onew$ repair method is better than the $\oold$?

<!-- tablev(ldt[Method=='old', Outcome], norm=T) -->
<!-- ##  failure  success  -->
<!-- ## 0.545455 0.454545  -->
<!-- tablev(ldt[Method=='new', Outcome], norm=T) -->
<!-- ##  failure  success  -->
<!-- ## 0.444444 0.555556  -->

<!-- tablev(ldt[Method=='old' & Location=='onsite', Outcome], norm=T) -->
<!-- ## failure success  -->
<!-- ##     0.2     0.8  -->
<!-- tablev(ldt[Method=='new' & Location=='onsite', Outcome], norm=T) -->
<!-- ## failure success  -->
<!-- ##    0.28    0.72  -->

<!-- tablev(ldt[Method=='old' & Location=='remote', Outcome], norm=T) -->
<!-- ##  failure  success  -->
<!-- ## 0.724138 0.275862  -->
<!-- tablev(ldt[Method=='new' & Location=='remote', Outcome], norm=T) -->
<!-- ##  failure  success  -->
<!-- ## 0.818182 0.181818  -->


:::

