# [Thanks]{.lightblue} {.unnumbered}
{{< include macros.qmd >}}

We would like to thank, in unsystematic order:

- The [master students]{.blue} of this course, for their enthusiasm and interest in the course goal and material, and for their constructive feedback. **You rock!**

- The members of the [*Artificial Intelligence Engineering*](https://github.com/HVL-ML) group at the Western Norway University of Applied Sciences (HVL) for endorsement of the present course and encouragement during its construction.

- [Soledad Gonzalo Cogno]{.blue} and [Iván Davidovich]{.blue} and their course [*Concepts in Data Analysis*](https://www.ntnu.edu/studies/courses/NEVR8011), organized by the [*Gonzalo Cogno Group*](https://www.ntnu.edu/kavli/gonzalo-cogno-group) at the [Kavli Institute for Systems Neuroscience](https://www.ntnu.edu/kavli) and at the Norwegian University of Science and Technology (NTNU), where some of the present course material was initially designed and tested.

- The members of the [*[Medical AI](https://mmiv.no/machinelearning/)*]{.blue} group at the [Mohn Medical Imaging and Visualization Centre](https://mmiv.no/), in particular Ingrid Rye, Alexandra Vik, Marek Kociński, Arvid Lundervold, Astri Lundervold, Alexander Lundervold, for the many group meetings, discussions, and projects where the core of the present course material was tested.

- The [*[Bulletin](https://bayesian.org/resources/bulletin/) of the [International Society for Bayesian Analysis](https://bayesian.org/)*]{.blue} and its editor [Gregor Kastner]{.blue} for kindly allowing us to share the present course in the "Teaching Highlight" section.

- [Lars Michael Kristensen]{.blue} for his great work on the [*Master in Applied Computer Science*](https://www.hvl.no/en/studies-at-hvl/study-programmes/ict-engineering-applied-computer-science-and-engineering/) at HVL, of which this course is part.

- The developers and maintainers of [[Quarto](https://quarto.org/)]{.blue} for help in the customization of this course's web pages.

- Our beloved, families, friends for their continuous encouragement and support.

- PGLPM thanks Saitama for being a constant source of awe and inspiration.
