# Truth inference and probability inference

## Logic: the rules for certain inference

Consider the following trivial but certain inference:
$$
\frac{
\textit{\small``My umbrella is either blue or red''}\quad
\textit{\small``My umbrella is not red''}
}{
\textit{\small``My umbrella is blue''}
}
$$
Above the line we write the sentences representing the data we have. Below the line we infer the information that supposedly interests us.

How could we draw this obvious inference? Which rules did we follow?

Logic is a huge field that formalizes and makes rigorous the rules that a rational person or an artificial intelligence should use in drawing certain inferences. We'll get a glimpse of it here, as a trampoline for jumping towards our data-driven engineering problems.

### Basic sentences

We start by writing down the _basic_^[A more technical term is "atomic"] sentences that constitute our data and that underlie the inferences we want to draw. "Basic" in the sense that we will not analyse these sentences into further sub-sentences. In the trivial example above we identify two such sentences: *"My umbrella is blue"*, and *"My umbrella is pink"*. Let's represent them by symbols:
$$
\begin{aligned}
b &\coloneqq \textit{\small``My umbrella is blue''}
\\
r &\coloneqq \textit{\small``My umbrella is red''}
\end{aligned}
$$

### Connectives

You notice that we didn't consider *"My umbrella is either blue or red"* and *"My umbrella is not red"* as basic sentences. These sentences can indeed be expressed in terms of the basic sentences $b$ and $r$. We consider one way or operation to change a sentence into another related to it, and two ways or operations to combine two or more sentences together. These operations are called "connectives". Our natural language offer many more operations to combine sentences, but these three turn out to be all we need in virtually all engineering problems. The three connectives are:

Not: $\lnot$
: for example,
$$
\lnot r = \textit{\small``My umbrella is not red''}
$$

And: $\land$
: for example,
$$
b \land r = \textit{\small``My umbrella is blue, and it is red''}
$$

Or: $\lor$
: for example,
$$
b \lor r = \textit{\small``My umbrella is blue, or it is red''}
$$

::: {.callout-warning appearance="simple"}
## 
Note some subtleties in 
:::





## Truth, falsity, and their consistency


## Inferences without uncertainty: the truth calculus

## Making room for uncertainty:<br>Plausibility, credibility, degree of belief, probability

## Inferences with uncertainty: the probability calculus

### The Three Fundamental Laws of inference

* _Exercise: [Monty-Hall problem & variations](The_Monty_Hall_problem-exercise.pdf)_

* _Exercise: clinical test & diagnosis_

### Bayes's theorem

## Common points of certain and uncertain inference

> _No premises? No conclusions!_
