<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ADA511: Data science and data-driven engineering - 19&nbsp; Exchangeability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./making_decisions.html" rel="next">
<link href="./population_inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,700;1,400;1,700&amp;family=IBM+Plex+Sans:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="ada511styles.css">
</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./recap.html">Population inference</a></li><li class="breadcrumb-item"><a href="./exchangeability.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Exchangeability</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./ada511logo8_small.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ADA511: <br>Data science and data-driven engineering</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">An invitation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Accept or discard?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic decision problems</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Inference – I</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">What is an inference?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sentences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./truth_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Truth inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data – I</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quantities and data types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_types_multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Joint quantities and complex data types</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Inference – II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Joint probability distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal_conditional_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Marginal and conditional probabilities</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Data – II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./populations_variates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Populations and variates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subpopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Subpopulations and conditional frequencies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Infinite populations and samples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Population inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Recap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./population_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference and populations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exchangeability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Exchangeability</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Decision theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Making decisions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Machine learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine_learning_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Machine learning - an introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#infinitely-exchangeable-populations" id="toc-infinitely-exchangeable-populations" class="nav-link active" data-scroll-target="#infinitely-exchangeable-populations"><span class="header-section-number">19.1</span> Infinitely exchangeable populations</a>
  <ul class="collapse">
  <li><a href="#definition" id="toc-definition" class="nav-link" data-scroll-target="#definition">Definition</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#consequences" id="toc-consequences" class="nav-link" data-scroll-target="#consequences">Consequences</a></li>
  </ul></li>
  <li><a href="#interpretations-of-exchangeability" id="toc-interpretations-of-exchangeability" class="nav-link" data-scroll-target="#interpretations-of-exchangeability"><span class="header-section-number">19.2</span> Interpretations of exchangeability</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Exchangeability</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="hidden">
<p><span class="math display">\[
\DeclarePairedDelimiters{\set}{\{}{\}}
\]</span></p>
</div>
<div class="hidden">

</div>
<p>The stock-exchange and Mars-prospecting inference problems of <a href="population_inference.html#sec-two-populations">§&nbsp;&nbsp;<span>18.2</span></a> differ in some aspects and are similar in others. Time, for example, seems an important aspect of the first inference. Yet, the second inference involves or could involve time as well: the rocks could be inspected sequentially. So more precisely it is the time <em>ordering</em> that seems more relevant in the first inference than the second.</p>
<p>An important difference between the two inference problems is revealed by the following thought-experiments. Consider how you would answer in the stock-exchange case and in the Mars-prospecting case:</p>
<ol type="a">
<li><p><span class="green"><em>It turns out that there was an error in the sequence of positive and negative datapoints, although not in the total amounts of positive and negative ones.</em></span> In the stock-exchange inference, for instance, days 1 (<span style="display:inline-block;"><span class="math inline">\(-\)</span>)</span> and 3 (<span style="display:inline-block;"><span class="math inline">\(+\)</span>)</span> were erroneously swapped, as were days 100 (<span style="display:inline-block;"><span class="math inline">\(+\)</span>)</span> and 85 (<span style="display:inline-block;"><span class="math inline">\(-\)</span>),</span> and many other days; in the Mars-prospecting inference, rocks #1 (Y) and #3 (N) were erroneously swapped, as were rocks #100 (Y) and #97 (N), and many other rocks.</p>
<ul>
<li><em>Should the final inference about the next 3 datapoints be changed?</em></li>
</ul></li>
<li><p><span class="green"><em>The information about the exact sequence of data is lost, and only the total amount of positive and negative datapoints is preserved</em></span> (74 vs 26).</p>
<ul>
<li><em>Would the final inference about the next 3 datapoints be different, compared to the situation where the exact data sequence is known?</em></li>
</ul></li>
<li><p><span class="green"><em>A new inference is requested: not about the 3 datapoints following the known data, but the 3 datapoints preceding the known data</em></span>: the day before day 1 and so on, or the rock before rock #1 and so on. (Or, generalizing: an inference about 3 datapoints <em>interspersed</em> among the known ones is requested.)</p>
<ul>
<li><em>Would the inference for the preceding 3 datapoints be different from the original one about the subsequent 3 datapoints?</em></li>
</ul></li>
</ol>
<p>In all these thought-experiments, our intuition is that the inference for the stock-exchange problem would be different, but the one for the Mars-prospecting problem would stay the same or not change appreciably. Swapping days in a stock course, matters; swapping rocks in a crater, doesn’t. There are good reasons, based on physics and dynamical-system theory, for this intuition.</p>
<p>An inference which does not change if data and unknown quantities are freely reordered, like the Mars-prospecting one, is called <span class="blue"><strong>exchangeable</strong></span>. Whereas an inference in which the ordering of data and unknowns is relevant, like the stock-exchange one, is called <strong>non-exchangeable</strong>. There is not a dichotomy between the two cases; rather, there are continuous varying degrees of exchangeability or non-exchangeability. But for the moment we shall simplify this gradation into a binary distinction.</p>
<p>We shall now make this definition more precise, and then study and exploit the remarkable consequences that it has for an agent’s inferences and probability calculations.</p>
<section id="infinitely-exchangeable-populations" class="level2 page-columns page-full" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="infinitely-exchangeable-populations"><span class="header-section-number">19.1</span> Infinitely exchangeable populations</h2>
<section id="definition" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="definition">Definition</h3>
<p>Consider a (practically) infinite statistical population with variate <span style="display:inline-block;"><span class="math inline">\(X\)</span>.</span> This variate could be a joint one, consisting of variates <span style="display:inline-block;"><span class="math inline">\(U,V,W,\dots\)</span></span> of arbitrary types. For simplicity let’s assume that the domain of this variate is discrete. For instance, the variate could be of a binary type with domain <span style="display:inline-block;"><span class="math inline">\(\set{\texttt{\small Yes}, \texttt{\small No}}\)</span>;</span> or it could be the combination of such a binary variate and an another ordinal variate with domain <span style="display:inline-block;"><span class="math inline">\(\set{\texttt{\small low}, \texttt{\small medium}, \texttt{\small high}}\)</span>;</span> so the domain of the joint variable would be the set of 2 × 3 values <span style="display:inline-block;"><span class="math inline">\(\set[\big]{(\texttt{\small Yes}, \texttt{\small low}),\ (\texttt{\small No}, \texttt{\small low}),\ \dotsc,\ (\texttt{\small No},\texttt{\small high})}\)</span>.</span></p>
<p>This variate associates a quantity to each unit in the population. We denote by <span style="display:inline-block;"><span class="math inline">\(X_1\)</span></span> the variate for unit #1, and so on.</p>
<p>Now consider an agent, with background knowledge <span style="display:inline-block;"><span class="math inline">\(\mathsfit{I}\)</span>,</span> which must draw inferences about some population units.</p>
<p><br>
</p>
<p>We call the infinite population <span class="blue"><strong>exchangeable</strong></span> if <span class="blue">the agent’s inferences are unaffected by the units’ identities, and only depend on the units’ variate values</span>. Said otherwise, <span class="blue">exchanges among the units’ identities don’t matter for inference purposes</span>.</p>
<p>Let’s make this clear with a simplified version of the Mars-prospecting example.</p>
<p>Suppose the agent knows the values of units #95–#99, and needs the probability that unit&nbsp;#101 has variate value <span style="display:inline-block;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span>,</span> unit&nbsp;#102 value <span style="display:inline-block;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span>,</span> and unit&nbsp;#103 value <span style="display:inline-block;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span>,</span> as schematized below:</p>
<div class="columns">
<div class="column" style="width:30%;">

</div><div class="column" style="width:30%;">
<table class="table-sm small table">
<caption></caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(H\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">95</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">96</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">97</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">98</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">99</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">100</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">101</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">102</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">103</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:40%;">

</div>
</div>
<p><span class="math display">\[
\mathrm{P}\bigl(H_{101}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ H_{102}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\ H_{103}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N}
\nonscript\:\big\vert\nonscript\:\mathopen{}
H_{99}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\ H_{98}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\
H_{97}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ H_{96}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\
H_{95}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ \mathsfit{I}\bigr)
\]</span></p>
<p><br>
</p>
<p>If the population is exchangeable, then the inference above is exactly the same – the probability values are identical – as the following one:</p>
<div class="columns">
<div class="column" style="width:30%;">

</div><div class="column" style="width:30%;">
<table class="table-sm small table">
<caption></caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(H\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">95</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">96</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">97</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">98</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">99</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">100</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">101</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">102</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">103</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\qquad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:40%;">

</div>
</div>
<p><span class="math display">\[
\mathrm{P}\bigl(H_{3}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ H_{7}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\ H_{97}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N}
\nonscript\:\big\vert\nonscript\:\mathopen{}
H_{1}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\ H_{5}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\
H_{95}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ H_{6}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{34,136,51}Y},\
H_{103}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small \color[RGB]{238,102,119}N},\ \mathsfit{I}\bigr)
\]</span></p>
<p>Why? Because both inferences have <span class="green">one <span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></span> and <span class="red">two <span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></span> in their supposals, and both have <span class="green">three <span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></span> and <span class="red">two <span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></span> in their conditionals. Or, from a different point of view, both inferences look the same if we reorder the units (each keeping its value), as shown below:</p>
<div class="column-page-right">
<div class="columns">
<div class="column" style="width:20%;">
<table class="table-sm small table">
<caption>2nd inference</caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(H\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">95</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">96</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">97</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">98</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">99</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">100</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">101</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">102</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">103</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:13%;">

</div><div class="column" style="width:20%;">
<table class="table-sm small table">
<caption>2nd inference reordered</caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(H\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">99</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">101</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">98</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">96</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">102</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">95</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">103</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">100</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">97</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:13%;">

</div><div class="column" style="width:20%;">
<table class="table-sm small table">
<caption>1st inference</caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(H\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">95</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">96</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">97</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">98</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">99</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{given}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">100</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">101</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">102</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{34,136,51}Y}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">103</span></td>
<td style="text-align: center;"><span class="math inline">\(\texttt{\small \color[RGB]{238,102,119}N}\)</span> <span class="math inline">\(\mathrlap{\quad\quad\textbf{?}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="midgrey">…</span></td>
<td style="text-align: center;"><span class="midgrey">…</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="column" style="width:14%;">

</div>
</div>
<p>Now consider an agent, with background knowledge <span style="display:inline-block;"><span class="math inline">\(\mathsfit{I}\)</span>,</span> which assigns a joint probability distribution over all the quantities <span style="display:inline-block;"><span class="math inline">\(X_1, X_2, X_3, \dotsc\)</span>:</span></p>
<p><span class="math display">\[
\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_1,\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_2,\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_3,\ \dotsc \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\]</span></p>
<p>for all possible combinations of values <span style="display:inline-block;"><span class="math inline">\(x_1, x_2, x_3, \dotsc\)</span>.</span></p>
<p><br>
</p>
<p>This joint probability distribution is called <span class="blue"><strong>infinitely exchangeable</strong></span> if <span class="blue"><em>all marginal probabilities (<a href="marginal_conditional_probability.html#sec-marginal-probs">§&nbsp;<span>12.1</span></a>) for any sub-collection of quantities remain the same whenever the values are swapped among quantities</em></span>. For example:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_2 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_3 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\\[1ex] {}={}&amp;
\mathrm{P}(X_{23} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_{7}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\end{aligned}
\]</span></p>
<p>and so on (they could all be equal to, say, <span style="display:inline-block;"><span class="math inline">\(0.012\)</span>);</span> and also</p>
<p><span class="math display">\[
\begin{aligned}
&amp;
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_2 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_2 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_3 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_5\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\\[1ex] {}={}&amp;
\mathrm{P}(X_{12} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_8\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_{47}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\end{aligned}
\]</span></p>
<p>and so on (all equal to, say, <span style="display:inline-block;"><span class="math inline">\(0.003\)</span>);</span> and also</p>
<p><span class="math display">\[
\begin{aligned}
&amp;
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c},\ X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{170,51,119}d}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\mathrm{P}(X_3 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c},\ X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{170,51,119}d}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\\[1ex] {}={}&amp;
\mathrm{P}(X_{91} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_{72}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_6\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c},\ X_{13}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{170,51,119}d}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\[1ex] {}={}&amp;
\dotso
\end{aligned}
\]</span></p>
<p>and so on – no matter how many and which quantities we take, and no matter what the values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}a},{\color[RGB]{102,204,238}b},{\color[RGB]{204,187,68}c},{\color[RGB]{170,51,119}d}\dotsc\)</span></span> might be.</p>
<p>In the following we shall simply call this type of probability distribution <span class="blue"><strong>exchangeable</strong></span>, omitting “infinitely”. But keep in mind that there are also <strong>finitely</strong> exchangeable distributions, and they have different properties from the infinitely exchangeable ones. </p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-exclamation-circle" aria-label="exclamation-circle"></i>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Exchangeability does not mean that <strong>all</strong> probabilities need to be equal. For instance, if <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}b}\ne{\color[RGB]{204,187,68}c}\)</span></span> then these probabilities can be different:</p>
<p><span class="math display">\[\begin{gathered}
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\mathrel{\boldsymbol{\ne}}
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\\
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\mathrel{\boldsymbol{\ne}}
\mathrm{P}(X_{23} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_7\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\end{gathered}\]</span></p>
<p>although we must still have</p>
<p><span class="math display">\[
\mathrm{P}(X_1 \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\mathrel{\boldsymbol{=}}
\mathrm{P}(X_{23} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_7\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\]</span></p>
</div>
</div>
<p>We shall give a concrete example of exchangeable distribution in a moment. As you realize, we are speaking of a distribution over an <em>infinite</em> number of quantities, so its values cannot be simply listed down, but must be given by a formula.</p>
<p><br>
</p>
<p>The definition of exchangeability given above can also be put in a different way. For an exchangeable probability distribution, <span class="blue"><em>the joint probability of a collection of quantities can only depend on the different values appearing in the collection and on and their multiplicities</em></span>. For instance, the numerical value of the marginal, joint probability</p>
<p><span class="math display">\[
\mathrm{P}(X_{91} \mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_{72}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{34,136,51}a},\ X_6\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{102,204,238}b},\ X_{13}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}{\color[RGB]{204,187,68}c}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\]</span></p>
<p>where <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}a},{\color[RGB]{102,204,238}b},{\color[RGB]{204,187,68}c}\)</span></span> are different from one another, can only depend on the fact that there are the three different values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}a},{\color[RGB]{102,204,238}b},{\color[RGB]{204,187,68}c}\)</span>,</span> and that <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}a}\)</span></span> appears once, <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}b}\)</span></span> twice, and <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}c}\)</span></span> once. So any other marginal, joint probability containing the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}a}\)</span></span> once, <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}b}\)</span></span> twice, and <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}c}\)</span></span> once, must be equal to the one above.</p>
<p><br>
</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>For each of the marginal probabilities below, determine whether the joint probability they come from is <em>surely <strong>non</strong>-exchangeable</em>, and explain why. Note that we can’t determine whether a probability distribution is exchangeable unless we’re given <em>all</em> its probabilities, for all combinations of quantities and values.<br>
</p>
<ol type="1">
<li><p><span class="math display">\[\begin{aligned}
&amp;\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3,\  X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.15
\\
&amp;\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5,\  X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.15
\\
&amp;\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}7,\  X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.25
\\
&amp;\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3,\  X_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}7\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.25
\end{aligned}
\]</span><br>
</p></li>
<li><p><span class="math display">\[\begin{aligned}
&amp;\mathrm{P}(Y_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3,\  Y_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.07
\\
&amp;\mathrm{P}(Y_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5,\  Y_4\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.07
\\
&amp;\mathrm{P}(Y_9\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3,\  Y_{21}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.4
\\
&amp;\mathrm{P}(Y_9\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}5,\  Y_{21}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.4
\end{aligned}
\]</span><br>
</p></li>
<li><p><span class="math display">\[\begin{aligned}
&amp;\mathrm{P}(Z_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high},\  Z_7\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low},\  Z_{20}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.11
\\
&amp;\mathrm{P}(Z_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high},\  Z_7\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high},\  Z_{20}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.35
\\
&amp;\mathrm{P}(Z_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low},\  Z_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low},\  Z_9\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0
\\
&amp;\mathrm{P}(Z_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high},\  Z_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low},\  Z_9\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{34,136,51}low}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0
\end{aligned}
\]</span><br>
</p></li>
<li><p><span class="math display">\[\begin{aligned}
&amp;\mathrm{P}(U_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}6.4,\  U_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}8.7,\  U_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}-0.3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.1
\\
&amp;\mathrm{P}(U_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}1.7,\  U_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}0.5,\  U_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}-0.3\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.1
\\
&amp;\mathrm{P}(U_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}-0.3,\  U_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}6.4,\  U_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}0.5\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.01
\\
&amp;\mathrm{P}(U_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}-0.3,\  U_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}1.7,\  U_3\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}0.5\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) = 0.4
\end{aligned}
\]</span></p></li>
</ol>
</div>
</div>
<p><br>
</p>
</section>
<section id="example" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>Consider the collection of ordinal quantities <span style="display:inline-block;"><span class="math inline">\(X_1, X_2, \dotsc\)</span></span> with common domain of three values <span style="display:inline-block;"><span class="math inline">\(\set{\texttt{\small\color[RGB]{34,136,51}low},\texttt{\small\color[RGB]{102,204,238}med},\texttt{\small\color[RGB]{204,187,68}high}}\)</span>.</span> The joint probability distribution for any set of these quantities is given by the formula</p>
<p><span class="math display">\[
\mathrm{P}(X_i\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_i,\ X_j\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_j,\ \dotsc \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I}) =
\frac{2\cdot \#\texttt{\small\color[RGB]{34,136,51}low}!\cdot \#\texttt{\small\color[RGB]{102,204,238}med}!\cdot \#\texttt{\small\color[RGB]{204,187,68}high}!}{(\#\texttt{\small\color[RGB]{34,136,51}low}+\#\texttt{\small\color[RGB]{102,204,238}med}+\#\texttt{\small\color[RGB]{204,187,68}high}+2)!}
\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The <em>factorial</em> <span style="display:inline-block;"><span class="math inline">\(n!\)</span></span> is defined by <span style="display:inline-block;"><span class="math inline">\(n! \coloneqq 1\cdot2\cdot\dotsb\cdot (n-1)\cdot n\)</span>,</span> and <span style="display:inline-block;"><span class="math inline">\(0!\coloneqq 1\)</span>.</span></p>
</div></div><p>where <span style="display:inline-block;"><span class="math inline">\(\#\texttt{\small\color[RGB]{34,136,51}low}\)</span></span> is the number of times the value <span style="display:inline-block;"><span class="math inline">\(\texttt{\small\color[RGB]{34,136,51}low}\)</span></span> appears among <span style="display:inline-block;"><span class="math inline">\(x_i,x_j,\dotsc\)</span>,</span> and similarly for <span style="display:inline-block;"><span class="math inline">\(\#\texttt{\small\color[RGB]{102,204,238}med}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\#\texttt{\small\color[RGB]{204,187,68}high}\)</span>.</span> For instance:</p>
<p><span class="math display">\[\begin{aligned}
\mathrm{P}( X_5\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{102,204,238}med},\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{204,187,68}high},\
X_{14}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}\texttt{\small\color[RGB]{102,204,238}med}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I}) &amp;=
\frac{2\cdot {\color[RGB]{34,136,51}0}!\cdot {\color[RGB]{102,204,238}2}!\cdot  {\color[RGB]{204,187,68}1}!}{({\color[RGB]{34,136,51}0} + {\color[RGB]{102,204,238}2} + {\color[RGB]{204,187,68}1} + 2)!}
\\[1ex]&amp;=
\frac{2\cdot {\color[RGB]{34,136,51}1}\cdot
{\color[RGB]{102,204,238}2}\cdot
{\color[RGB]{204,187,68}1}}{5!}
\\&amp;=
\frac{4}{120}
\\[1ex]&amp;\approx 0.0333
\end{aligned}\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p><span class="green"><span class="math inline">\(\texttt{\small\color[RGB]{34,136,51}low}\)</span> doesn’t appear</span><br>
<span class="lightblue"><span class="math inline">\(\texttt{\small\color[RGB]{102,204,238}med}\)</span> appears twice</span><br>
<span class="yellow"><span class="math inline">\(\texttt{\small\color[RGB]{204,187,68}high}\)</span> appears once</span></p>
</div></div><div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the formula above, verify that the marginal probability distribution for two units <span style="display:inline-block;"><span class="math inline">\(\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_1,\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_2 \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})\)</span>,</span> where <span style="display:inline-block;"><span class="math inline">\(x_1, x_2\)</span></span> can each take on the values <span style="display:inline-block;"><span class="math inline">\(\texttt{\small\color[RGB]{34,136,51}low}, \texttt{\small\color[RGB]{102,204,238}med}, \texttt{\small\color[RGB]{204,187,68}high}\)</span>,</span> satisfies</p>
<p><span class="math display">\[
\sum_{x_1} \sum_{x_2}
\mathrm{P}(X_1\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_1,\ X_2\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_2 \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I}) = 1
\]</span></p>
<p>as it should (hint: you have to sum nine terms).</p>
</div>
</div>
<p>Why are we focusing on exchangeable probability distributions? Because their mathematical properties have an interesting interpretation, very useful for particular kinds of inferences. We shall now explore this interpretation.</p>
</section>
<section id="consequences" class="level3">
<h3 class="anchored" data-anchor-id="consequences">Consequences</h3>
<p>The stock-exchange and Mars-prospecting inference problems do not involve simple joint probabilities like</p>
<p><span class="math display">\[\mathrm{P}(X_{101}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{101},\ X_{102}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{102},\ \dotsc \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})\]</span></p>
<p>but conditional probabilities like</p>
<p><span class="math display">\[\mathrm{P}(X_{101}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{101},\ X_{102}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{102},\ \dotsc \nonscript\:\vert\nonscript\:\mathopen{}
X_{100}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{100},\ X_{99}\mathrel{\mkern-2.5mu\textrm{\small=}\mkern-2.5mu}x_{99},\ \dotsc,\ \mathsfit{I})\]</span></p>
<p>because the problem is to infer some datapoints given other datapoints. What does exchangeability say about conditional probabilities?</p>
<p>It can be proved that</p>
</section>
</section>
<section id="interpretations-of-exchangeability" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="interpretations-of-exchangeability"><span class="header-section-number">19.2</span> Interpretations of exchangeability</h2>
<p>Our focus, however, is not on the <em>whys</em> of this intuition, but on the consequences that it has for inference and probability calculations.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./population_inference.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference and populations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./making_decisions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Making decisions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>