<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-11-13">

<title>ADA511 0.1 Data science and data-driven engineering - 36&nbsp; From inferences to decisions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./connection-4-ML.html" rel="next">
<link href="./example_opm1.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="ada511styles.css">
</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./making_decisions.html"><span class="lightblue"><strong>Decision theory</strong></span></a></li><li class="breadcrumb-item"><a href="./making_decisions.html"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">[From inferences to decisions]{.blue}</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./ada511logo8_small.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ADA511 <span class="small grey">0.1</span> <br><span class="small grey">updated 2023-11-13</span></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dear student<br> and aspiring data engineer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text"><strong>An invitation</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Accept or discard?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic decision problems</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-1-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="red">First connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><span class="green">What is an inference?</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><span class="green">Sentences</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./truth_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><span class="green">Truth inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title"><span class="green">Probability inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./derived_rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title"><span class="green">Shortcut rules</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title"><span class="green">Monty Hall and related inference problems</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-2-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><span class="red">Second connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title"><span class="yellow">Quantities and data types</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types_multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><span class="yellow">Joint quantities and complex data types</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title"><span class="green">Probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title"><span class="green">Joint probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title"><span class="green">Marginal probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title"><span class="green">Conditional probability and learning</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><span class="green">Information, relevance, independence, association</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-3-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><span class="red">Third connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./populations_variates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><span class="yellow">Populations and variates</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title"><span class="yellow">Statistics</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subpopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><span class="yellow">Subpopulations and conditional frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title"><span class="yellow">Infinite populations and samples</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text"><span class="red"><strong>Machine learning</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine_learning_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduction to machine learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference III</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./beyond-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title"><span class="red">Beyond machine learning</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exchangeable_probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title"><span class="green">Exchangeable beliefs</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_from_freqs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title"><span class="green">Inferences from frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_about_freqs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><span class="green">Inference about frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary_formulae.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title"><span class="green">Final inference formulae</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text"><span class="red"><strong>A prototype Optimal Predictor Machine</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dirichlet-mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title"><span class="red">The Dirichlet-mixture belief distribution</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title"><span class="red">Code design</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prototype_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title"><span class="red">Prototype code and workflow</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_opm1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title"><span class="red">Example application: adult-income task</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text"><span class="lightblue"><strong>Decision theory</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making_decisions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title"><span class="blue">From inferences to decisions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-4-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title"><span class="blue">Decisions: limitations of present-day machine-learning algorithms</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#accept-or-discard-again" id="toc-accept-or-discard-again" class="nav-link active" data-scroll-target="#accept-or-discard-again"><span class="header-section-number">36.1</span> Accept or discard? – again</a></li>
  <li><a href="#sec-decisions-utilities" id="toc-sec-decisions-utilities" class="nav-link" data-scroll-target="#sec-decisions-utilities"><span class="header-section-number">36.2</span> Outcomes, decisions, utilities</a></li>
  <li><a href="#sec-max-exp-utilities" id="toc-sec-max-exp-utilities" class="nav-link" data-scroll-target="#sec-max-exp-utilities"><span class="header-section-number">36.3</span> Maximization of expected utility</a>
  <ul class="collapse">
  <li><a href="#numerical-implementation-in-simple-cases" id="toc-numerical-implementation-in-simple-cases" class="nav-link" data-scroll-target="#numerical-implementation-in-simple-cases">Numerical implementation in simple cases</a></li>
  </ul></li>
  <li><a href="#sec-max-exp-util-example" id="toc-sec-max-exp-util-example" class="nav-link" data-scroll-target="#sec-max-exp-util-example"><span class="header-section-number">36.4</span> Concrete example: targeted advertisement</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#powerful-flexibility-of-the-optimal-predictor-machine" id="toc-powerful-flexibility-of-the-optimal-predictor-machine" class="nav-link" data-scroll-target="#powerful-flexibility-of-the-optimal-predictor-machine">Powerful flexibility of the optimal predictor machine</a></li>
  </ul></li>
  <li><a href="#sec-whence-utilities" id="toc-sec-whence-utilities" class="nav-link" data-scroll-target="#sec-whence-utilities"><span class="header-section-number">36.5</span> How to determine utilities?</a>
  <ul class="collapse">
  <li><a href="#heterogeneous-factors" id="toc-heterogeneous-factors" class="nav-link" data-scroll-target="#heterogeneous-factors">Heterogeneous factors</a></li>
  <li><a href="#uncertainty" id="toc-uncertainty" class="nav-link" data-scroll-target="#uncertainty">Uncertainty</a></li>
  <li><a href="#approximate-assignments" id="toc-approximate-assignments" class="nav-link" data-scroll-target="#approximate-assignments">Approximate assignments</a></li>
  </ul></li>
  <li><a href="#sec-DT-generalization" id="toc-sec-DT-generalization" class="nav-link" data-scroll-target="#sec-DT-generalization"><span class="header-section-number">36.6</span> The full extent of Decision Theory</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-from-inf-to-dec" class="quarto-section-identifier"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title"><span class="blue">From inferences to decisions</span></span></span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2023-11-13</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="hidden">
<p><span class="math display">\[
\DeclarePairedDelimiters{\set}{\{}{\}}
\DeclareMathOperator*{\argmax}{argmax}
\]</span></p>
</div>
<div class="hidden">

</div>
<section id="accept-or-discard-again" class="level2 page-columns page-full" data-number="36.1">
<h2 data-number="36.1" class="anchored" data-anchor-id="accept-or-discard-again"><span class="header-section-number">36.1</span> Accept or discard? – again</h2>
<p>Our very first example of engineering problem (<a href="intro.html">chapter&nbsp;&nbsp;<span>1</span></a>) in these lecture notes was the decision whether to accept or discard an electronic component just produced in an assembly line. In <a href="basic_decisions.html">chapter&nbsp;&nbsp;<span>3</span></a> we met the theory to deal with this kind of decision-making problem: Decision Theory.</p>
<p>We saw that Decision Theory requires the agent, who’s making the decision, to calculate the probabilities of the unknown outcomes. All our discussion and chapters thereafter focused on the calculation of those probabilities, which often is the most difficult part of the decision making task.</p>
<p>At long last we have the knowledge to calculate such probabilities, both for general problems, and more in detail problems enjoying special properties, for instance when the agent’s beliefs are exchangeable (<a href="exchangeable_probabilities.html">chapter&nbsp;&nbsp;<span>28</span></a>). Most important, we saw how previous data and background information can be used to determine these probabilities, and how they influence and modify these probabilities. We have even built a real, prototype agent that can flexibly calculate probabilities in problems involving nominal variates.</p>
<div class="page-columns page-full"><p>Let’s face the decision-making problem again, and complete the construction of our prototype agent by implementing the final decision-making step.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Please go back to <a href="basic_decisions.html">chapter&nbsp;&nbsp;<span>3</span></a> and review the notions and terminology introduced there.</p></li></div></div>
</section>
<section id="sec-decisions-utilities" class="level2" data-number="36.2">
<h2 data-number="36.2" class="anchored" data-anchor-id="sec-decisions-utilities"><span class="header-section-number">36.2</span> Outcomes, decisions, utilities</h2>
<p>Recall the structure of a basic decision:</p>
<p><img src="basic_decision_tree.png" class="img-fluid" style="width:100.0%"></p>
<p>In order to make a decision, the agent needs:</p>
<ul>
<li><p><i class="fa-solid fa-cube" aria-label="cube"></i> The set of possible <span class="yellow"><em>decisions</em></span>, which we represent as sentences like <span style="display:inline-block;"><span class="math inline">\(\mathsfit{\color[RGB]{204,187,68}D}\)</span>.</span></p></li>
<li><p><i class="fa-solid fa-cube" aria-label="cube"></i> The set of possible <span class="red"><em>outcomes</em></span>, whose truth is unknown to the agent. In the kind of decision problems that we are examining, the outcomes correspond to the possible values <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y\)</span></span> of what we have called the <span class="red">predictand</span> variate from <a href="beyond-ML.html#sec-cat-problems">§ &nbsp;<span>27.2</span></a> onwards.</p></li>
<li><p><i class="fa-solid fa-cube" aria-label="cube"></i> The <span class="green"><em>probabilities</em></span> of the outcomes&nbsp;&nbsp;<span style="display:inline-block;"><span class="math inline">\(\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})\)</span></span> which are determined by the agent’s background information <span style="display:inline-block;"><span class="math inline">\(\mathsfit{I}\)</span>,</span> by any other available information, such as <span style="display:inline-block;"><span class="math inline">\(\mathsfit{\color[RGB]{34,136,51}data}\)</span></span> about previously observed units and the values of some predictor variates <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x\)</span></span> for the current unit; and possibly also by the agent’s decision <span style="display:inline-block;"><span class="math inline">\(\mathsfit{\color[RGB]{204,187,68}D}\)</span></span> (see below).</p></li>
<li><p><i class="fa-solid fa-cube" aria-label="cube"></i> The <span class="blue"><em>utilities</em></span> of the decisions and the outcomes, which we denote</p>
<p><span class="math display">\[
\mathrm{U}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{204,187,68}D}\nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
\]</span></p>
<p>This notation reminds us that the utilities assigned by the agent also depend on its background information <span style="display:inline-block;"><span class="math inline">\(\mathsfit{I}\)</span>.</span></p></li>
</ul>
<p>Some texts call the joint pair <span style="display:inline-block;"><span class="math inline">\(({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{204,187,68}D})\)</span>,</span> of a decision and an outcome, a <span class="blue"><strong>consequence</strong></span>. We adopt this terminology from this chapter onward.</p>
<p>Let’s not forget some important points about the notions above:</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-exclamation-triangle" aria-label="exclamation-triangle"></i>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>We are not assuming any temporal or “causal” relationship between <span class="yellow">decisions</span> and <span class="red">outcomes</span>: <strong>our framework works independently of these relationships</strong>. In some decision-making problems the outcomes happen <em>after</em> a decision is made, and may be “influenced” by it or not. In other decision-making problems the outcomes have already happened <em>before</em> a decision is made.</p>
<p>In a transportation-choice problem, for instance, the outcome “<span class="red">wet from rain</span>” may happen after we make the decision “<span class="yellow">go on foot</span>” rather than “<span class="yellow">go by bus</span>”. In an image-classification problem, on the other hand, the outcome “<span class="red">true label is <span class="math inline">\({\small\verb;cat;}\)</span></span>” was already determined before we made the decision “<span class="yellow">classify as <span class="math inline">\({\small\verb;dog;}\)</span></span>”.</p></li>
</ul>
<p><br>
</p>
<ul>
<li><p>In connection with the warning above, in some problems the probabilities of the outcomes may depend on the decision; that is, knowledge about the decision is <em>relevant</em> to the knowledge about the outcome (see again <a href="information.html">§ &nbsp;<span>18</span></a>):</p>
<p><span class="math display">\[\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})\]</span></p>
<p>For instance, in the transportation-choice problem the probability of the outcome “<span class="red">wet from rain</span>” is higher conditional on the decision “<span class="yellow">go on foot</span>” than on the decision “<span class="yellow">go by bus</span>”.</p>
<p>In many decision-making problems typical of machine learning, such as classification, information about the decision is <em>irrelevant</em> to the information about the outcome (which usually has already happened), and we have</p>
<p><span class="math display">\[
  \mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
  = \mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
  \]</span></p></li>
</ul>
</div>
</div>
<p>In what follows we shall consider problems, such as classification, where knowledge of the agent’s decision is irrelevant to the outcome’s probability. We shall nevertheless keep the more general notation&nbsp;&nbsp;<span style="display:inline-block;"><span class="math inline">\(\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})\)</span>.</span></p>
</section>
<section id="sec-max-exp-utilities" class="level2 page-columns page-full" data-number="36.3">
<h2 data-number="36.3" class="anchored" data-anchor-id="sec-max-exp-utilities"><span class="header-section-number">36.3</span> Maximization of expected utility</h2>
<p>The expected utility of each possible decision <span style="display:inline-block;"><span class="math inline">\(\mathsfit{\color[RGB]{204,187,68}D}\)</span></span> is calculated as a weighted average over all possible outcomes:</p>
<p><span class="math display">\[\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}\nonscript\:\vert\nonscript\:\mathopen{}\mathsfit{I})
= \sum_{\color[RGB]{238,102,119}y} \mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I}) \cdot
\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
\]</span></p>
<p>The agent’s final decision satisfies the</p>
<div class="column-page-right">
<div class="callout callout-style-default callout-note no-icon callout-titled" style="font-size:120%">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span style="font-size:110%"><strong>Principle of maximal expected utility</strong></span>
</div>
</div>
<div class="callout-body-container callout-body">
<div style="font-size:120%">
<p>The optimal decision, which should be made by the agent, is the one with maximal expected utility:</p>
<p><span class="math display">\[
\mathsfit{\color[RGB]{204,187,68}D}_{\text{optimal}} =
\argmax_{\mathsfit{\color[RGB]{204,187,68}D}} \sum_{\color[RGB]{238,102,119}y} \mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I}) \cdot
\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
\]</span></p>
<p>(where, in some tasks, the probabilities may not depend on <span style="display:inline-block;"><span class="math inline">\(\mathsfit{\color[RGB]{204,187,68}D}\)</span>)</span></p>
</div>
</div>
</div>
</div>
<p><span class="small midgrey">In the formula above, <span style="display:inline-block;">“<span class="math inline">\(\argmax\limits_z G(z)\)</span>”</span> is the value <span class="math inline">\(z\)</span> which maximizes <span class="math inline">\(G(z)\)</span>. Note the difference: <span class="math inline">\(\max\limits_z G(z)\)</span> is the value of the maximum itself, whereas <span class="math inline">\(\argmax\limits_z G(z)\)</span> is the value of the <em>argument</em> that gives the maximum. For instance&nbsp;&nbsp;<span class="math inline">\(\max\limits_z (1-z)^2 = 0\)</span>,&nbsp;&nbsp;but&nbsp;&nbsp;<span class="math inline">\(\argmax\limits_z (1-z)^2 = 1\)</span>.</span></p>
<p>It may happen that there are several decisions which have equal, maximal expected utilities. In this case any one of them can be chosen. A useful strategy is to choose one among them with equal probability (such strategy helps minimizing the loss from possible small errors in the specification of the utilities, or from the presence of an antagonist agent which tries to predict what our agent is doing).</p>
<section id="numerical-implementation-in-simple-cases" class="level3">
<h3 class="anchored" data-anchor-id="numerical-implementation-in-simple-cases">Numerical implementation in simple cases</h3>
<p>The principle of maximal expected utility is straightforward to calculate in many important problems. First, the collection of expected utilities can be obtained with a simple matrix multiplication. We represent the utilities for all consequences (that is, pairs of decisions and outcomes) with a matrix <span style="display:inline-block;"><span class="math inline">\(\boldsymbol{\color[RGB]{68,119,170}U}\)</span>,</span> having one row per decision and one column per outcome:</p>
<p><span class="math display">\[
\boldsymbol{\color[RGB]{68,119,170}U}\coloneqq
\begin{bmatrix}
\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}' \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}' \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
&amp;
\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}' \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}'' \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
&amp; \dotso
\\
\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}'' \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}' \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
&amp;
\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}'' \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}'' \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})
&amp; \dotso
\\
\dotso&amp;\dotso&amp;\dotso
\end{bmatrix}
\]</span></p>
<p>If the probabilities of the outcomes do <strong>not</strong> depend on the decisions, we represent them as a column matrix <span style="display:inline-block;"><span class="math inline">\(\boldsymbol{\color[RGB]{34,136,51}P}\)</span>,</span> having one entry per outcome:</p>
<p><span class="math display">\[
\boldsymbol{\color[RGB]{34,136,51}P}\coloneqq
\begin{bmatrix}
\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}' \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
\\
\mathrm{P}({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y}'' \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{\color[RGB]{34,136,51}data}\mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})
\\
\dotso
\end{bmatrix}
\]</span></p>
<p>Then the collection of expected utilities is a column matrix, having one entry per decision, given by the matrix product <span style="display:inline-block;"><span class="math inline">\(\boldsymbol{\color[RGB]{68,119,170}U}\boldsymbol{\color[RGB]{34,136,51}P}\)</span>.</span> All that’s left is to check which of the entries in this final matrix is maximal.</p>
</section>
</section>
<section id="sec-max-exp-util-example" class="level2 page-columns page-full" data-number="36.4">
<h2 data-number="36.4" class="anchored" data-anchor-id="sec-max-exp-util-example"><span class="header-section-number">36.4</span> Concrete example: targeted advertisement</h2>
<p>As a concrete example, let’s keep on using the adult-income task from <a href="example_opm1.html">chapter&nbsp;&nbsp;<span>35</span></a>, in a typical present-day scenario.</p>
<p>Some corporation, which offers a particular phone app, wants to <a href="https://pluralistic.net/2023/07/24/rent-to-pwn/">bombard its users with advertisements</a>, because advertisement generates much more revenue than making the users pay for the app. For each user the corporation can choose one among three ad-types, let’s call them <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}A}, {\color[RGB]{204,187,68}B}, {\color[RGB]{204,187,68}C}\)</span>.</span> The revenue obtained from these ad-types depends on whether the target user’s income is <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}{\small\verb;&lt;=50K;}}\)</span></span> or <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}{\small\verb;&gt;50K;}}\)</span>.</span> A separate study run by the corporation has shown that the average revenues (per user per minute) depending on the three ad-types and the income levels are as follows:</p>
<div class="columns">
<div class="column" style="width:25%;">

</div><div class="column" style="width:50%;">
<div id="tbl-income" class="anchored">
<table class="table-sm small table">
<caption>Table&nbsp;36.1: Revenue depending on ad-type and income level</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<tbody>
<tr class="odd">
<td colspan="2" rowspan="2" style="text-align: center;"></td>
<td colspan="2" style="text-align: right;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}income}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\({\color[RGB]{238,102,119}{\small\verb;&lt;=50K;}}\)</span></td>
<td style="text-align: right;"><span class="math inline">\({\color[RGB]{238,102,119}{\small\verb;&gt;50K;}}\)</span></td>
</tr>
<tr class="odd">
<td rowspan="3" style="text-align: center;"><span class="yellow">ad-type</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{204,187,68}A}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}-1\,\$\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}3\,\$\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{204,187,68}B}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}2\,\$\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}2\,\$\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{204,187,68}C}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}3\,\$\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\color[RGB]{68,119,170}-1\,\$\)</span></td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:25%;">

</div>
</div>
<p>Ad-type <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}B}\)</span></span> is a neutral advertisement type that leads to revenue independently of the target user’s income. Ad-type <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}A}\)</span></span> targets high-income users, leading to higher revenue from them; but it leads to a loss if shown to the wrong target (more money spent on making and deploying the ad than what is gained from users’ purchases). Vice versa, ad-type <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}B}\)</span></span> targets low-income users, with a reverse effect.</p>
<p>The corporation doesn’t have access to its users’ income levels, but it covertly collects, through some other app, all or some of the eight predictor variates <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{workclass}\)</span>,</span> <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{education}\)</span>,</span> <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\dotsc\)</span>,</span> <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{sex}\)</span>,</span> <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{native\_country}\)</span></span> from each of its users. The corporation has also access to the adult-income dataset (or let’s say a more recent version of it).</p>
<p>In this scenario the corporation would like to use an AI agent that can choose and show the optimal ad-type to each user.</p>
<p><br>
</p>
<p>Our prototype agent from chapters&nbsp;<a href="code_design.html"><span>33</span></a>, <a href="prototype_code.html"><span>34</span></a>, <a href="example_opm1.html"><span>35</span></a> can be used for such a task. It has already been trained with the dataset, and can use any subset (possibly even empty) of the eight predictors to calculate the probability for the two income levels.</p>
<p>All that’s left is to equip our prototype agent with a function that outputs the optimal decision, given the calculated probabilities and the set of utilities. In our code this is done by the function <code>decide()</code> described in <a href="prototype_code.html">chapter&nbsp;&nbsp;<span>34</span></a>:</p>
<div class="small">
<blockquote class="blockquote">
<p><i class="fa-solid fa-code" aria-label="code"></i> <a href="https://github.com/pglpm/ADA511/blob/master/code/OPM-nominal/decide.R"><code>decide(probs, utils=NULL, all=FALSE)</code></a></p>
<dl>
<dt>Arguments:</dt>
<dd>
<ul>
<li><em><code>probs</code></em>: a probability distribution for one or more variates.</li>
<li><em><code>utils</code></em>: a named matrix or array of utilities. The <strong>rows</strong> of the matrix correspond to the available decisions, the <strong>columns</strong> or remaining array dimensions correspond to the possible values of the predictand variates.</li>
<li><em><code>all</code></em>: a boolean, <code>TRUE</code> if the output should have all decisions having maximal expected utilities (if more than one); <code>FALSE</code> (default) if the output should only have one of them, selected with equal probabilities.</li>
</ul>
</dd>
<dt>Output:</dt>
<dd>
<ul>
<li>a vector of strings with the decisions having maximal expected utility, if <em><code>all</code></em> is <code>TRUE</code>, or just one of them, selected with equal probability, if <em><code>all</code></em> is <code>FALSE</code> (the default).</li>
</ul>
</dd>
<dt>Notes:</dt>
<dd>
<ul>
<li>If <em><code>utils</code></em> is missing or <code>NULL</code>, a matrix of the form <span class="math inline">\(\begin{bsmallmatrix}1&amp;0&amp;\dotso\\0&amp;1&amp;\dotso\\\dotso&amp;\dotso&amp;\dotso\end{bsmallmatrix}\)</span> is assumed (which corresponds to using <em>accuracy</em> as evaluation metric).</li>
</ul>
</dd>
</dl>
</blockquote>
</div>
<section id="example" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>A new user logs in; all eight predictors are available for this user:</p>
<div class="small">
<p><span class="math display">\[\color[RGB]{34,136,51}
\begin{aligned}
&amp;\mathit{workclass} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Private;}
&amp;&amp; \mathit{education} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Bachelors;}
\\ &amp; \mathit{marital\_status} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Never-married;}
&amp;&amp; \mathit{occupation} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Prof-specialty;}
\\ &amp; \mathit{relationship} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Not-in-family;}
&amp;&amp; \mathit{race} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;White;}
\\ &amp; \mathit{sex} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Female;}
&amp;&amp; \mathit{native\_country} \mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;United-States;}
\end{aligned}
\]</span></p>
</div>
<p>The agent calculates (using the <code>infer()</code> function) the probabilities for the two income levels, which turn out to be</p>
<div class="small">
<p><span class="math display">\[
\begin{aligned}
&amp;\mathrm{P}({\color[RGB]{238,102,119}\mathit{\color[RGB]{238,102,119}income}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{238,102,119}{\small\verb;&lt;=50K;}}} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{34,136,51}predictor}, \mathsfit{\color[RGB]{34,136,51}data}, \mathsfit{I}) = 83.3\%
\\&amp;\mathrm{P}({\color[RGB]{238,102,119}\mathit{\color[RGB]{238,102,119}income}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{238,102,119}{\small\verb;&gt;50K;}}} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{34,136,51}predictor}, \mathsfit{\color[RGB]{34,136,51}data}, \mathsfit{I}) = 16.7\%
\end{aligned}
\]</span></p>
</div>
<p>and can be represented by the column matrix</p>
<p><span class="math display">\[\boldsymbol{\color[RGB]{34,136,51}P}\coloneqq
\begin{bmatrix}
0.833\\0.167
\end{bmatrix}
\]</span></p>
<p>The utilities previously given can be represented by the matrix</p>
<p><span class="math display">\[\boldsymbol{\color[RGB]{68,119,170}U}\coloneqq
\begin{bmatrix}
-1&amp;3\\2&amp;2\\3&amp;-1
\end{bmatrix}
\]</span></p>
<p>Multiplying the two matrices above we obtain the expected utilities of the three ad-types for the present user:</p>
<div class="column-body-outset-right">
<p><span class="math display">\[
\boldsymbol{\color[RGB]{68,119,170}U}\boldsymbol{\color[RGB]{34,136,51}P}=
\color[RGB]{68,119,170}\begin{bmatrix}
-1&amp;3\\2&amp;2\\3&amp;-1
\end{bmatrix}
\,
\color[RGB]{34,136,51}\begin{bmatrix}
0.833\\0.167
\end{bmatrix}\color[RGB]{0,0,0}
=
\begin{bmatrix}
{\color[RGB]{68,119,170}-1}\cdot{\color[RGB]{34,136,51}0.833}
+ {\color[RGB]{68,119,170}3}\cdot{\color[RGB]{34,136,51}0.167}
\\
{\color[RGB]{68,119,170}2}\cdot{\color[RGB]{34,136,51}0.833}
+ {\color[RGB]{68,119,170}2}\cdot{\color[RGB]{34,136,51}0.167}
\\
{\color[RGB]{68,119,170}3}\cdot{\color[RGB]{34,136,51}0.833}
+ ({\color[RGB]{68,119,170}-1})\cdot{\color[RGB]{34,136,51}0.167}
\end{bmatrix}
=
\begin{bmatrix}
-0.332\\
2.000\\
\boldsymbol{2.332}
\end{bmatrix}
\]</span></p>
</div>
<p>The highest expected utility is that of ad-type <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{204,187,68}C}\)</span>,</span> which is therefore shown to the user.</p>
</section>
<section id="powerful-flexibility-of-the-optimal-predictor-machine" class="level3">
<h3 class="anchored" data-anchor-id="powerful-flexibility-of-the-optimal-predictor-machine">Powerful flexibility of the optimal predictor machine</h3>
<p>In the previous chapters we already emphasized and witnessed the flexibility of the optimal predictor machine with regard to the availability of the predictors: it can draw an inference even if some or all predictors are missing.</p>
<p>Now we can see another powerful kind of flexibility: the optimal predictor machine can in principle <em>use different sets of decisions and different utilities for each new application</em>. The decision criterion is not “hard-coded”; it can be customized on the fly.</p>
<p>The possible number of ad-types and the utilities could even be a function of the predictor values. For instance, there could be a set of three ad-types targeting users with <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{education}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Bachelors;}\)</span>,</span> a different set of four ad-types targeting users with <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{34,136,51}\mathit{education}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;Preschool;}\)</span>,</span> and so on.</p>
<p><br>
</p>
</section>
</section>
<section id="sec-whence-utilities" class="level2 page-columns page-full" data-number="36.5">
<h2 data-number="36.5" class="anchored" data-anchor-id="sec-whence-utilities"><span class="header-section-number">36.5</span> How to determine utilities?</h2>
<p>It can be quite difficult to assess the utilities of the decisions and outcomes in a decision-making problems, because of several reasons discussed below. Yet, Decision Theory says that any decision is either implicitly using such a number, or is sub-optimal or logically inconsistent. Moreover, the specification, at some level, of utilities not derived by further analysis is simply unavoidable – just like the specification of some initial probabilities.</p>
<section id="heterogeneous-factors" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="heterogeneous-factors">Heterogeneous factors</h3>
<p>Many heterogeneous factors can enter the determination of utilities. In medical decision-making problems, for example, a clinician must choose one among several possible treatments for a patient, and the utilities of the outcome must take into account factors such as</p>
<ul>
<li>cost of the treatment</li>
<li>expected life length resulting from the treatment</li>
<li>quality of life resulting from the treatment</li>
<li>patient’s preferences and attitudes towards life</li>
</ul>
<p>It can be very difficult to combine these factors into a single number.</p>
<p>Several fields, such as medicine, have developed and refined several methodologies to arrive at utilities that account for all important factors. Unfortunately we shall not explore any of them in these notes.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-rocket" aria-label="rocket"></i> For the extra curious
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Chapter&nbsp;8 of <a href="https://hvl.instructure.com/courses/25074/modules/items/671397"><em>Medical Decision Making</em></a></li>
<li><a href="https://hvl.instructure.com/courses/25074/modules/items/729855"><em>Decisions with Multiple Objectives</em></a></li>
</ul>
</div>
</div>
</div></div></section>
<section id="uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="uncertainty">Uncertainty</h3>
<p>The assessment of utilities can also be affected by uncertainties, and therefore become an inference problem in itself. The utility of an outcome may depend on further decisions and further outcomes, whose utilities in turn depend on further decisions and outcomes. Our basic decision framework can in this case be applied repeatedly, as briefly discussed below. In the simplest case, if the agent is uncertain between utility values <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}\boldsymbol{\color[RGB]{68,119,170}U}'\)</span></span> with probability <span style="display:inline-block;"><span class="math inline">\(p'\)</span>,</span> and utility values <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}\boldsymbol{\color[RGB]{68,119,170}U}''\)</span></span> with probability <span style="display:inline-block;"><span class="math inline">\(p'' = 1-p'\)</span>,</span> then the utilities to use are the averages</p>
<p><span class="math display">\[p'\,{\color[RGB]{68,119,170}\boldsymbol{\color[RGB]{68,119,170}U}'} + p''\,{\color[RGB]{68,119,170}\boldsymbol{\color[RGB]{68,119,170}U}''}\]</span></p>
<p>But the specification, at some level, of utilities not derived by further inferences is simply unavoidable – just like the specification of some initial probabilities.</p>
</section>
<section id="approximate-assignments" class="level3">
<h3 class="anchored" data-anchor-id="approximate-assignments">Approximate assignments</h3>
<p>An approximate procedure of assigning utilities goes as follows:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">

</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Write down all possible consequences</p></li>
<li><p>Sort all consequences from best to worst. Ties are possible, that is, there may be several consequences considered to be equally good or equally bad.</p></li>
<li><p>Assign utility <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}1\)</span></span> to the best consequence (or to each of the best, if there’s a tie), and utility <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}0\)</span></span> to the worst.</p></li>
<li><p>Determine the utility <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{68,119,170}u}\)</span></span> of each intermediate consequence <span style="display:inline-block;"><span class="math inline">\(({\color[RGB]{238,102,119}y}, \mathsfit{\color[RGB]{204,187,68}D})\)</span></span> as follows:</p>
<ol type="a">
<li>Consider a <em>lottery</em> where you can win the best consequence (that with utility <span class="math inline">\(\color[RGB]{68,119,170}1\)</span>) with some probability <span class="math inline">\(p^{+}\)</span>, or the worst consequence with probability <span class="math inline">\(1-p^{+}\)</span>.</li>
<li>Choose one value of <span class="math inline">\(p^{+}\in [0,1]\)</span> such that it would be OK if you were forced to exchange the lottery with the consequence <span class="math inline">\(({\color[RGB]{238,102,119}y},\mathsfit{\color[RGB]{204,187,68}D})\)</span> under consideration, <em>and vice versa</em>, exchange the consequence under consideration with the lottery.</li>
<li>That probability value is the utility <span class="math inline">\({\color[RGB]{68,119,170}u}= p^{+}\)</span> of the consequence under consideration.</li>
</ol></li>
<li><p>Check whether the utilities determined through lotteries respect your initial sorting. If they don’t, then you have reasoned inconsistently somewhere. Repeat the steps above thinking more thoroughly about your sorting and lotteries.</p></li>
<li><p>As an additional check, take any three consequences with utilities <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{68,119,170}u}_1 \ge {\color[RGB]{68,119,170}u}_2 \ge {\color[RGB]{68,119,170}u}_3\)</span>.</span> Consider again a lottery where you can win the <em>first</em> consequence with probability <span style="display:inline-block;"><span class="math inline">\(p\)</span></span> or the <em>third</em> with probability <span style="display:inline-block;"><span class="math inline">\(1-p\)</span>,</span> and choose <span style="display:inline-block;"><span class="math inline">\(p\)</span></span> so that it would be OK to be forced to exchange this lottery with the <em>second</em> consequence, and vice versa. Then you should find, at least approximately, that</p>
<p><span class="math display">\[{\color[RGB]{68,119,170}u}_2 = p\cdot {\color[RGB]{68,119,170}u}_1 + (1-p)\cdot {\color[RGB]{68,119,170}u}_3\]</span></p>
<p>If you don’t, then there are again inconsistencies or irrational biases in your judgements, and you should review them.</p></li>
</ol>
</div>
</div>
<p>In the procedure above, the values <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}1\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{68,119,170}0\)</span></span> for the best and worst consequences are arbitrary: they correspond to setting a zero and a measurement unit of your utility scale. You can choose any other pair of values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{68,119,170}u_{\textrm{max}}} &gt; {\color[RGB]{68,119,170}u_{\textrm{min}}}\)</span>.</span> The procedure applies in the same way, but the utility corresponding to <span style="display:inline-block;"><span class="math inline">\(p^{+}\)</span></span> is then given by</p>
<p><span class="math display">\[{\color[RGB]{68,119,170}u}= p^{+}\cdot{\color[RGB]{68,119,170}u_{\textrm{max}}} +
(1-p^{+})\cdot {\color[RGB]{68,119,170}u_{\textrm{min}}}
\]</span></p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-book" aria-label="book"></i> Study reading
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>§ 15.3.1 of <a href="https://hvl.instructure.com/courses/25074/modules/items/660089"><em>Artificial Intelligence</em></a></p></li>
<li><p>Final <strong>Summary</strong> (pp.&nbsp;234–235) of chapter&nbsp;8 in <a href="https://hvl.instructure.com/courses/25074/modules/items/671397"><em>Medical Decision Making</em></a></p></li>
<li><p>§§&nbsp;9.14–9.17 of <a href="https://hvl.instructure.com/courses/25074/modules/items/660091"><em>Making Decisions</em></a></p></li>
<li><p>§ 4.2 of <a href="https://hvl.instructure.com/courses/25074/modules/items/729855"><em>Decisions with Multiple Objectives</em></a></p></li>
<li><p>Skim through <a href="https://hvl.instructure.com/courses/25074/modules/items/729862"><em>Attitude and opinion measurement</em></a></p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="sec-DT-generalization" class="level2" data-number="36.6">
<h2 data-number="36.6" class="anchored" data-anchor-id="sec-DT-generalization"><span class="header-section-number">36.6</span> The full extent of Decision Theory</h2>
<p>The simple decision-making problems and framework that we have discussed in these notes are only the basic blocks of Decision Theory. This theory covers more complicated decision problems. We only mention some examples:</p>
<ul>
<li><strong>Sequential decisions</strong>. As mentioned in the previous section, many decision-making problems involve sequences of possible decisions, alternating with sequences of possible outcomes. These sequences can be represented as decision trees. Decision theory allows us to find the optimal decision sequence for instance through the <em>averaging out and folding back” procedure</em>.</li>
</ul>
<div class="small">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-rocket" aria-label="rocket"></i> For the extra curious
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>§ 15.5 and chapter&nbsp;16 of <a href="https://hvl.instructure.com/courses/25074/modules/items/660089"><em>Artificial Intelligence</em></a></li>
<li>Chapter&nbsp;2 of <a href="https://hvl.instructure.com/courses/25074/modules/items/664382"><em>Decision Analysis</em></a></li>
</ul>
</div>
</div>
</div>
<p><br>
</p>
<ul>
<li><p><strong>Uncertain utilities</strong>. It is possible to recast Decision Theory and the principle of maximum expected utility in terms, not of utility functions <span style="display:inline-block;"><span class="math inline">\(\mathrm{U}(\mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{I})\)</span>,</span> but of probability distributions over utility values:</p>
<p><span class="math display">\[\mathrm{P}({\color[RGB]{68,119,170}U\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}u} \nonscript\:\vert\nonscript\:\mathopen{} \mathsfit{\color[RGB]{204,187,68}D}\mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathsfit{I})\]</span></p>
<p>Formally the two approaches can be shown to be equivalent.</p></li>
</ul>
<div class="small">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-rocket" aria-label="rocket"></i> For the extra curious
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Chapter&nbsp;8 of <a href="https://hvl.instructure.com/courses/25074/modules/items/664392"><em>Rational Descriptions, Decisions and Designs</em></a></li>
<li>Box 11.1 (p. 351) of <a href="https://hvl.instructure.com/courses/25074/modules/items/664427"><em>Risk Assessment and Decision Analysis with Bayesian Networks</em></a></li>
</ul>
</div>
</div>
</div>
<p><br>
</p>
<ul>
<li><strong>Acquiring more information</strong>. In many situations the agent has one more possible choice: to gather more information in order to calculate sharper probabilities, rather than deciding immediately. This kind of decision is also accounted for by Decision Theory, and constitutes one of the theoretical bases of “reinforcement learning”.</li>
</ul>
<div class="small">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-rocket" aria-label="rocket"></i> For the extra curious
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>§ 15.6 of <a href="https://hvl.instructure.com/courses/25074/modules/items/660089"><em>Artificial Intelligence</em></a></li>
<li>§ 11.5 of <a href="https://hvl.instructure.com/courses/25074/modules/items/664427"><em>Risk Assessment and Decision Analysis with Bayesian Networks</em></a></li>
</ul>
</div>
</div>
</div>
<p><br>
</p>
<ul>
<li><strong>Multi-agent problems</strong>. To some extent it is possible to consider situations (such as games) with several agents having different and even opposing utilities. This area of Decision Theory is apparently still under development.</li>
</ul>
<div class="small">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-rocket" aria-label="rocket"></i> For the extra curious
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Chapter&nbsp;17 of <a href="https://hvl.instructure.com/courses/25074/modules/items/660089"><em>Artificial Intelligence</em></a></li>
</ul>
</div>
</div>
</div>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./example_opm1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title"><span class="red">Example application: adult-income task</span></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./connection-4-ML.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title"><span class="blue">Decisions: limitations of present-day machine-learning algorithms</span></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>