<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-08-11">

<title>ADA511 0.1 Data science and data-driven engineering - 19&nbsp; Populations and variates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./statistics.html" rel="next">
<link href="./2nd_connection_ML.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="ada511styles.css">
</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./populations_variates.html"><span class="yellow"><strong>Data II</strong></span></a></li><li class="breadcrumb-item"><a href="./populations_variates.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">[Populations and variates]{.yellow}</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./ada511logo8_small.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ADA511 <span class="small grey">0.1</span> <br><span class="small grey">updated 2023-08-11</span></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dear student<br> and aspiring data engineer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text"><strong>An invitation</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Accept or discard?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic decision problems</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0th_connection_ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="red">First connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><span class="green">What is an inference?</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><span class="green">Sentences</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./truth_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><span class="green">Truth inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title"><span class="green">Probability inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./derived_rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title"><span class="green">Shortcut rules</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title"><span class="lightblue">Monty Hall and related inference problems</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1st_connection_ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><span class="red">Second connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title"><span class="yellow">Quantities and data types</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types_multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><span class="yellow">Joint quantities and complex data types</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title"><span class="green">Probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title"><span class="green">Joint probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title"><span class="green">Marginal probabilities</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title"><span class="green">Conditional probabilities</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2nd_connection_ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><span class="red">Third connection with machine learning</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./populations_variates.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><span class="yellow">Populations and variates</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><span class="yellow">Statistics</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subpopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title"><span class="yellow">Subpopulations and conditional frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><span class="yellow">Infinite populations and samples</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Population inference</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title"><span class="green">A general inference problem</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./population_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title"><span class="green">Inference and populations</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exchangeability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title"><span class="green">Exchangeability</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_exchangeability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title"><span class="green">Inference under exchangeability</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missing_parts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">To be written</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glass_application_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title"><span class="red">The optimal predictor machine in action (for nominal quantities)</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text"><span class="lightblue"><strong>Decision theory</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title"><span class="lightblue">Making decisions</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text"><span class="red"><strong>Machine learning</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine_learning_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Machine learning - an introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-collections" id="toc-sec-collections" class="nav-link active" data-scroll-target="#sec-collections"><span class="header-section-number">19.1</span> Collections of similar quantities</a></li>
  <li><a href="#sec-variates-populations" id="toc-sec-variates-populations" class="nav-link" data-scroll-target="#sec-variates-populations"><span class="header-section-number">19.2</span> Units, variates, statistical populations</a></li>
  <li><a href="#populations-with-joint-variates" id="toc-populations-with-joint-variates" class="nav-link" data-scroll-target="#populations-with-joint-variates"><span class="header-section-number">19.3</span> Populations with joint variates</a>
  <ul class="collapse">
  <li><a href="#joint-frequencies" id="toc-joint-frequencies" class="nav-link" data-scroll-target="#joint-frequencies">Joint frequencies</a></li>
  </ul></li>
  <li><a href="#marginal-populations" id="toc-marginal-populations" class="nav-link" data-scroll-target="#marginal-populations"><span class="header-section-number">19.4</span> Marginal populations</a></li>
  <li><a href="#marginal-frequencies" id="toc-marginal-frequencies" class="nav-link" data-scroll-target="#marginal-frequencies"><span class="header-section-number">19.5</span> Marginal frequencies</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-variates" class="quarto-section-identifier"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><span class="yellow">Populations and variates</span></span></span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2023-08-11</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="hidden">
<p><span class="math display">\[
\DeclarePairedDelimiters{\set}{\{}{\}}
\DeclareMathOperator*{\argmax}{arg\,max}
\]</span></p>
</div>
<div class="hidden">

</div>
<section id="sec-collections" class="level2 page-columns page-full" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="sec-collections"><span class="header-section-number">19.1</span> Collections of similar quantities</h2>
<p>In engineering and data science, we often face inference problems involving not just one quantity (simple, joint, or complex), but collections of quantities. And in many problems all quantities in the collection have the same domain, so they can somehow be considered as “instances” of the same kind of quantity. Consider the following examples:</p>
<ul>
<li><dl>
<dt><a href="https://www.britannica.com/money/topic/stock-exchange-finance">Stock exchange</a></dt>
<dd>
We are interested in the daily change in <a href="https://www.investor.gov/introduction-investing/investing-basics/glossary/closing-price">closing price</a> of a stock, during 100 days. Each day the change can be <span class="green">positive (or zero)</span>, or <span class="yellow">negative</span>.
</dd>
</dl>
The daily change on any day can clearly be considered as a binary quantity, say with domain <span class="math inline">\(\set{+, -}\)</span>. The daily changes in 100 days are a set of 100 binary quantities with exactly the same domain – even if each one can have a different value.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="stock_course.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><p><br>
</p>
<ul>
<li><dl>
<dt>Mars <a href="https://www.britannica.com/technology/prospecting-mining">prospecting</a></dt>
<dd>
Some robot examines 100 similar-sized rocks in a large crater on Mars. Each rock either <span class="green">contains <a href="https://science.nasa.gov/science-news/science-at-nasa/2001/ast28mar_1">hematite</a></span>, or it <span class="yellow">doesn’t</span>.
</dd>
</dl>
The hematite-content of any rock can be considered as a binary quantity, say with domain <span class="math inline">\(\set{\texttt{\small Y}, \texttt{\small N}}\)</span>. The hematite contents of the 100 rocks are again a set of 100 binary quantities with exactly the same domain – even if each one can have a different value.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="mars_crater2.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><p>It is easy to think of many other and very diverse examples that are similar to the two above. We shall now try to abstract and generalize this similarity.</p>
</section>
<section id="sec-variates-populations" class="level2 page-columns page-full" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="sec-variates-populations"><span class="header-section-number">19.2</span> Units, variates, statistical populations</h2>
<p>Consider a large collection of entities that are somehow similar to one another. We call these entities <span class="blue"><strong>units</strong></span>. These units could be, for instance:</p>
<ul>
<li>physical objects such as cars, windmills, planets, or rocks from a particular place;</li>
<li>creatures such as animals of a particular species, or human beings, maybe with something in common such as geographical region; or plants of a particular kind;</li>
<li>automatons having a particular application;</li>
<li>software objects such as photos;</li>
<li>abstract objects such as functions or graphs;</li>
<li>the rolls of a particular die or the tosses of a particular coin;</li>
<li>the weather conditions in several days.</li>
</ul>
<div class="page-columns page-full"><p>These units are similar to one another in that they have some attribute<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> common to all. This attribute can present itself in a specific number of mutually-exclusive guises, which can be different from unit to unit. For instance, the attribute could be:</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;The term <span class="blue"><em>feature</em></span> is used in machine learning</p></li></div></div>
<ul>
<li>“colour”, each unit being, say, <span class="green">green</span>, <span class="blue">blue</span>, or <span class="yellow">yellow</span>;</li>
<li>“mass”, each unit having a mass between <span class="math inline">\(0.1\,\mathrm{kg}\)</span> and <span class="math inline">\(10\,\mathrm{kg}\)</span>;</li>
<li>“health condition”, each unit (an animal or human in this case) being <code>healthy</code> or <code>ill</code>; or maybe being affected by one of a specific set of diseases;</li>
<li>containing something, for instance a particular chemical substance;</li>
<li>“having a label”, each unit having one of the labels <code>A</code>, <code>B</code>, <code>C</code>;</li>
<li>a complex combination of several simpler attributes like the ones above.</li>
</ul>
<p>The units also have additional attributes (they must, otherwise we wouldn’t be able to distinguish each unit from all others), which we simply don’t consider or can’t measure. We’ll discuss this possibility later.</p>
<p>From this description it’s clear that the attribute of each unit is a <em>quantity</em>, as defined in <a href="quantities_types.html#sec-quant-value-dom">§&nbsp;<span>12.1.1</span></a>. Once the units and their attribute are specified, we have a set of as many quantities as there are units. All these quantities have identical domains.</p>
<p>A quantity which is an “attribute” of a set of units is called a <span class="blue"><strong>variate</strong></span>. So when we speak about a variate it is understood that this is a quantity that appears, replicated, in some set of units.</p>
<p><br>
</p>
<p>We call a collection of units so defined a <span class="blue"><strong>statistical population</strong></span>, or just <strong>population</strong> when there’s no ambiguity. The number of units is called the <span class="blue">size</span> of the population.</p>
<p>The notion of statistical population is extremely general and encompassing; so many different things can be thought of as a population. In speaking of “data”, what is often meant is a particular statistical population. The specification of a population requires precision, especially when it is used to draw inferences, as we shall see later. A statistical population has not truly been specified until two things are precisely given:</p>
<ul>
<li>a way to determine whether something is a unit or not: inclusion and exclusion criteria, means of collection, and so on</li>
<li>a definition of the variate considered, its possible values, and how it is measured</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercises
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Which of the following descriptions does define a statistical population? explain why it does or does not.</p>
<ol type="1">
<li><p>People.</p></li>
<li><p>Electronic components produced in a specific assembly line, since the line became operational until its discontinuation, and measured for their electric resistance, with possible values in <span style="display:inline-block;"><span class="math inline">\([0\,\mathrm{\Omega}, \infty\,\mathrm{\Omega}]\)</span>,</span> and result of a shock test, with possible values <span style="display:inline-block;"><span class="math inline">\(\set{\texttt{\small pass}, \texttt{\small fail}}\)</span>.</span></p></li>
<li><p>People born in Norway between 1st January 1990 and 31st December 2010.</p></li>
<li><p>The words contained on all websites of the internet.</p></li>
<li><p>Rocks, of volume between 1 cm³ and 1 m³, found in the <a href="https://www.esa.int/ESA_Multimedia/Images/2015/11/On_the_rim_of_Schiaparelli_crater">Schiaparelli crater</a> (as defined by contours on a map), and tested to contain hematite, with possible values <span style="display:inline-block;"><span class="math inline">\(\set{\texttt{\small Y}, \texttt{\small N}}\)</span>.</span></p></li>
</ol></li>
<li><p>Browse some <a href="https://archive.ics.uci.edu/datasets">datasets at the UC Irvine Machine Learning repository</a>. Each dataset is a statistical population. The variate in most of these populations is a joint variate (to be discussed soon), that is, a collection of several variates.</p>
<p>Examine and discuss the specification of some of those datasets:</p>
<ul>
<li>Is it well-specified what constitutes a “unit”? Are the criteria for including or excluding datapoints, their origin, and so on, well explained?</li>
<li>Are the variates well-defined? Is it explained what they mean, how they were measured, what is their domain, and so on?</li>
</ul></li>
</ul>
</div>
</div>
<p><br>
</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-exclamation-circle" aria-label="exclamation-circle"></i> Subtleties in the notion of statistical population
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>A statistical population is only a conceptual device to simplify and face some decision or inference problem. There is no objectively-defined population “out there”.</p>
<p>Any entity, object, person, and so on has characteristic that makes it completely unique (say, its space-time coordinates), otherwise we wouldn’t be able to distinguish it from others. From this point of view any entity is just be a one-member population in itself. If we consider two or more entities as being “similar” and belonging to the same population, it’s because we have decided to disregard some characteristics and focus on some others. This decision is arbitrary, a matter of convention, and depends on the specific inference and decision problem.</p>
<p>To “test” whether an entity belong to a given population, means to check if that entity satisfies the agreed-upon definition of that population.</p></li>
<li><p>Any physical entity, object, person, etc. can represent different units in different and even non-overlapping statistical populations. For instance, a 100 cm³ rock found in the Schiaparelli crater on Mars could be a unit in these populations:</p>
<ol type="a">
<li>Rocks, of volume between 1 cm³ and 1 m³, found in the Schiaparelli crater and tested for hematite</li>
<li>Rocks, of volume between 10 cm³ and 200 cm³, found in the Schiaparelli crater and tested for hematite</li>
<li>Rocks, of volume between 10 cm³ and 200 m³, found in any crater on any planet of the solar system, and tested for hematite</li>
<li>Rocks, of volume between 1 cm³ and 1 m³, found in the Schiaparelli crater and measured for the magnitude of their <a href="https://www.feynmanlectures.caltech.edu/II_34.html">magnetic field</a>.</li>
</ol>
<p>Populations a. b. c.&nbsp;above have the same variate but differ in their definition of “unit”. Populations a. and d.&nbsp;have the same definition of unit but different variates. Population b. is a subset of population a.: they have the same variate, and any unit in b. is also a unit in a. Populations a. and c.&nbsp;have some overlap: they have the same variate, and some units of a. are also units of c., and vice versa.</p></li>
</ul>
</div>
</div>
</section>
<section id="populations-with-joint-variates" class="level2 page-columns page-full" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="populations-with-joint-variates"><span class="header-section-number">19.3</span> Populations with joint variates</h2>
<p>The definition of statistical population (<a href="#sec-variates-populations">§&nbsp;&nbsp;<span>19.2</span></a>) makes it clear that the quantity associated with each unit can be of arbitrary complexity. In particular it could be a joint quantity (<a href="quantities_types_multi.html#sec-data-multiv">§&nbsp;&nbsp;<span>13.1</span></a>), that is, a collection of quantities of a simpler type.</p>
<p>As an example, consider the following population, relevant for <a href="https://www.fbi.gov/about-us/lab/forensic-science-communications/fsc/april2009/review/2009_04_review01.htm">glass forensics</a>:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="glass_fragments.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><ul>
<li><em>units:</em> glass fragments (collected at specific locations)</li>
<li><em>variate:</em> the joint variate <span class="math inline">\((\mathit{RI}, \mathit{Ca}, \mathit{Si}, \mathit{Type})\)</span> consisting of four simple variates:
<ul>
<li><a href="https://www.feynmanlectures.caltech.edu/I_26.html#Ch26-S2"><span class="math inline">\(\mathit{R}\)</span>efractive <span class="math inline">\(\mathit{I}\)</span>ndex</a> of the glass fragment (interval continuous variate), with domain from <span class="math inline">\(1\)</span> (included) to <span class="math inline">\(+\infty\)</span></li>
<li>weight percent of <a href="https://pubchem.ncbi.nlm.nih.gov/element/Calcium"><span class="math inline">\(\mathit{Ca}\)</span>lcium</a> in the fragment (interval discrete variate), with domain from <span class="math inline">\(0\)</span> to <span class="math inline">\(100\)</span> in steps of 0.01</li>
<li>weight percent of <a href="https://pubchem.ncbi.nlm.nih.gov/element/14"><span class="math inline">\(\mathit{Si}\)</span>licon</a> in the fragment (interval discrete variate), with domain from <span class="math inline">\(0\)</span> to <span class="math inline">\(100\)</span> in steps of 0.01</li>
<li><span class="math inline">\(\mathit{Type}\)</span> of glass fragment (nominal variate), with seven possible values <code>building_windows_float_processed</code>, <code>building_windows_non_float_processed</code>, <code>vehicle_windows_float_processed</code>, <code>vehicle_windows_non_float_processed</code>, <code>containers</code>, <code>tableware</code>, <code>headlamps</code></li>
</ul></li>
</ul>
<div id="tbl-glass" class="anchored">
<table class="table-sm small table">
<caption>Table&nbsp;19.1: Glass fragments</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{RI}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51888\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.95\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72.50\)</span></td>
<td style="text-align: center;"><code>tableware</code></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51556\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.41\)</span></td>
<td style="text-align: center;"><span class="math inline">\(73.23\)</span></td>
<td style="text-align: center;"><code>headlamps</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51645\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.08\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72.65\)</span></td>
<td style="text-align: center;"><code>building_windows_non_float_processed</code></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\(1.52247\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\(70.26\)</span></td>
<td style="text-align: center;"><code>headlamps</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51909\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.78\)</span></td>
<td style="text-align: center;"><span class="math inline">\(71.81\)</span></td>
<td style="text-align: center;"><code>building_windows_float_processed</code></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51590\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.22\)</span></td>
<td style="text-align: center;"><span class="math inline">\(73.10\)</span></td>
<td style="text-align: center;"><code>building_windows_non_float_processed</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51610\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.32\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72.69\)</span></td>
<td style="text-align: center;"><code>vehicle_windows_float_processed</code></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51673\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.03\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72.53\)</span></td>
<td style="text-align: center;"><code>building_windows_non_float_processed</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">9</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51915\)</span></td>
<td style="text-align: center;"><span class="math inline">\(10.09\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72.69\)</span></td>
<td style="text-align: center;"><code>containers</code></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">10</span></td>
<td style="text-align: center;"><span class="math inline">\(1.51651\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\(73.61\)</span></td>
<td style="text-align: center;"><code>headlamps</code></td>
</tr>
</tbody>
</table>
</div>
<p>The joint-variate value for <span class="yellow">unit 4</span>, for instance, is</p>
<p><span class="math display">\[
\mathit{RI}_{\color[RGB]{204,187,68}4}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}1.52247 \land
\mathit{Ca}_{\color[RGB]{204,187,68}4}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}9.76 \land
\mathit{Si}_{\color[RGB]{204,187,68}4}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}70.26 \land
\mathit{Type}_{\color[RGB]{204,187,68}4}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small headlamps}
\]</span></p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-exclamation-circle" aria-label="exclamation-circle"></i>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The units’ IDs don’t need to be consecutive numbers; in fact they don’t even need to be numbers: any label that completely distinguishes all units will do.</p>
</div>
</div>
<section id="joint-frequencies" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="joint-frequencies">Joint frequencies</h3>
<div class="page-columns page-full"><p>The frequency distribution for the joint variate of the population above gives the frequencies of all possible combinations of variate values. In this population, ten joint values appear each only once, and the remaining values never appear; this is because of the population’s small size and the large number of possible variate values. Denoting by <span style="display:inline-block;"><span class="math inline">\(\boldsymbol{f}\)</span></span> the joint frequency distribution, we have for example<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;For the continuous variate <span style="display:inline-block;"><span class="math inline">\(\mathit{RI}\)</span>,</span> the frequency refers to a small range around the value; see the discussion in (§&nbsp;<a href="probability_distributions.html#sec-prob-densities"><span>Section&nbsp;14.3</span></a>). In the present case the range seems to be <span style="display:inline-block;"><span class="math inline">\(\pm 0.000 01\)</span></span></p></li></div></div>
<p><span class="math display">\[\begin{aligned}
&amp;f(\mathit{RI}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}1.51651  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Ca}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}9.76 \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Si}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}73.61  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Type}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small headlamps}
) = \frac{1}{10}
\\
&amp;f(\mathit{RI}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}1.0  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Ca}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}50.00  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Si}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}50.00  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Type}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small tableware}
) = 0
\end{aligned}\]</span></p>
</section>
</section>
<section id="marginal-populations" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="marginal-populations"><span class="header-section-number">19.4</span> Marginal populations</h2>
<p>When a population has a joint variate, we may be interested in only a subset of the simpler variates that constitute the joint one. In the glass-forensics population above, for instance, we might be interested only in the <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span>lcium</span> and <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> variates. These two variates together are called <span class="blue"><strong>marginal variates</strong></span> and define what we can call a <span class="blue"><strong>marginal population</strong></span> of the original one. A marginal population has the same units as the original one, but only a subset of the variates of the original. It is a statistical population in its own right.</p>
<p>The notion of “marginalization” is a relative notion. Any population can often be considered as the marginal of a population with the same units but additional attributes.</p>
</section>
<section id="marginal-frequencies" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="marginal-frequencies"><span class="header-section-number">19.5</span> Marginal frequencies</h2>
<p>Given a statistical population with joint variates <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}X}, {\color[RGB]{238,102,119}Y}\)</span>,</span> we define the <span class="blue"><strong>marginal frequency</strong></span> of the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}y}\)</span></span> of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}Y}\)</span></span> as the frequency of the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}y}\)</span></span> in the marginal population with the variate <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}Y}\)</span></span> alone. This frequency is simply written</p>
<p><span class="math display">\[
f({\color[RGB]{238,102,119}Y\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}y})
\]</span></p>
<p>A conditional frequency can be calculated as the sum of the joint frequencies for all values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}x}\)</span>,</span> in a way analogous to marginal probabilities (<a href="marginal_probability.html#sec-marginal-probs">§&nbsp;&nbsp;<span>16.1</span></a>):</p>
<p><span class="math display">\[
f({\color[RGB]{238,102,119}Y\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}y}) = \sum_{\color[RGB]{238,102,119}y} f({\color[RGB]{238,102,119}Y\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}y} \mathbin{\mkern-0mu,\mkern-0mu}{\color[RGB]{34,136,51}X\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}x})
\]</span></p>
<p>For example, if from the population of <a href="#tbl-glass">table&nbsp;&nbsp;<span>19.1</span></a> we consider the marginal population with variates <span style="display:inline-block;"><span class="math inline">\((\mathit{Ca}, \mathit{Type})\)</span></span> marginal population, we find the marginal frequencies</p>
<p><span class="math display">\[\begin{aligned}
&amp;f(\mathit{Ca}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}9.76 \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Type}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small headlamps}
) = \frac{2}{10}
\\
&amp;f(\mathit{Ca}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}10.09 \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Type}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small containers}
) = \frac{1}{10}
\\
&amp;f(\mathit{Ca}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}50.00  \mathbin{\mkern-0mu,\mkern-0mu}
\mathit{Type}\mathord{\nonscript\mkern 1.5mu\textrm{\small=}\nonscript\mkern 1.5mu}\mathopen{}\texttt{\small tableware}
) = 0
\end{aligned}\]</span></p>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./2nd_connection_ML.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><span class="red">Third connection with machine learning</span></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./statistics.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><span class="yellow">Statistics</span></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>