<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-09-01">

<title>22&nbsp; Subpopulations and conditional frequencies – ADA511 [0.3]{.small .grey} &lt;br&gt;Data Science and AI prototyping</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./samples.html" rel="next">
<link href="./statistics.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6fc7f9edc9275b1be4df9d56d9e5af00.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="ada511styles.css">
</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><span class="yellow">Subpopulations and conditional frequencies</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./ada511logo8_small.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ADA511 <span class="small grey">0.3</span><br><span class="small grey">2025-09-01</span><br></a><a href="http://creativecommons.org/licenses/by-sa/4.0"><img src="cc_by_sa.png" class="img-fluid" style="width:3em" alt="CC BY-SA 4.0"> <span class="small grey">licence</span></a><br> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dear student<br> and aspiring data- &amp; AI-engineer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="lightblue"><strong>An invitation</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><span class="lightblue">Accept or discard?</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><span class="lightblue">Framework</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="lightblue">Basic decision problems</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-1-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="midgrey">Connection with machine learning and AI</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><span class="green">What is an inference?</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><span class="green">Sentences</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./truth_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><span class="green">Truth inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title"><span class="green">Probability inference</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./derived_rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title"><span class="green">Shortcut rules</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title"><span class="green">Monty Hall and related inference problems</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-2-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><span class="midgrey">Second connection with machine learning</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data I</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title"><span class="yellow">Quantities and data types</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quantities_types_multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><span class="yellow">Joint quantities and complex data types</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title"><span class="green">Probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title"><span class="green">Joint probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginal_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title"><span class="green">Marginal probability distributions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title"><span class="green">Conditional probability and learning</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional_summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="green">Learning and conditional probability: a summary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><span class="green">Information, relevance, independence, association</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./connection-3-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><span class="midgrey">Third connection with machine learning</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="yellow"><strong>Data II</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./populations_variates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><span class="yellow">Populations and variates</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title"><span class="yellow">Statistics</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subpopulations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><span class="yellow">Subpopulations and conditional frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title"><span class="yellow">Infinite populations and samples</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="midgrey"><strong>Machine learning</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine_learning_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduction to machine learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./llms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Large Language Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="green"><strong>Inference III</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./beyond-ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title"><span class="green">Beyond machine learning</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exchangeable_probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title"><span class="green">Exchangeable beliefs</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_from_freqs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title"><span class="green">Inferences from frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_about_freqs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><span class="green">Inference about frequencies</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary_formulae.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title"><span class="green">Final inference formulae</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="red"><strong>A prototype Optimal Predictor Machine</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dirichlet-mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title"><span class="red">The Dirichlet-mixture belief distribution</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title"><span class="red">Code design</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prototype_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title"><span class="red">Prototype code and workflow</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_opm1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title"><span class="red">Example application: adult-income task</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="blue"><strong>Decision-making</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./utilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title"><span class="blue">Utilities</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making_decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title"><span class="blue">Making decisions</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_opm2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title"><span class="red">The prototype Optimal Predictor Machine makes decisions</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="midgrey"><strong>Further connections with present-day machine-learning</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./limitations_ML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title"><span class="midgrey">Decisions: limitations of present-day machine-learning algorithms</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./utilities_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title"><span class="midgrey">Evaluation practices and utilities</span></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text"><span class="lightblue"><strong>Conclusion</strong></span></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./whither.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="lightblue">What next?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="lightblue">Further reading</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./thanks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="lightblue">Thanks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="lightblue">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-subpopulations" id="toc-sec-subpopulations" class="nav-link active" data-scroll-target="#sec-subpopulations"><span class="header-section-number">22.1</span> Subpopulations</a></li>
  <li><a href="#sec-conditional-freqs" id="toc-sec-conditional-freqs" class="nav-link" data-scroll-target="#sec-conditional-freqs"><span class="header-section-number">22.2</span> Conditional frequencies</a></li>
  <li><a href="#sec-association" id="toc-sec-association" class="nav-link" data-scroll-target="#sec-association"><span class="header-section-number">22.3</span> Associations</a>
  <ul class="collapse">
  <li><a href="#associations-can-be-very-counter-intuitive" id="toc-associations-can-be-very-counter-intuitive" class="nav-link" data-scroll-target="#associations-can-be-very-counter-intuitive">Associations can be very counter-intuitive</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><span class="yellow">Subpopulations and conditional frequencies</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2025-09-01</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="hidden">
<p><span class="math inline">\(\DeclarePairedDelimiter{\set}{\{}{\}}\)</span> </p>
</div>
<div class="hidden">

</div>
<section id="sec-subpopulations" class="level2 page-columns page-full" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="sec-subpopulations"><span class="header-section-number">22.1</span> Subpopulations</h2>
<p>When we have a statistical population with a joint variate, it is often of interest to focus on a subset of units that share the same value of a particular variate.</p>
<p>Consider for instance the following population, related to the glass-forensics example we encountered before:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="glass_fragments.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><ul>
<li><em>units:</em> glass fragments (collected at specific locations)</li>
<li><em>variate:</em> the joint variate <span class="math inline">\((\mathit{Ca}, \mathit{Si}, \mathit{Type})\)</span> consisting of three simple variates:
<ul>
<li>weight fraction of <span class="math inline">\(\mathit{Ca}\)</span>lcium in the fragment (ordinal variate), with three possible values <span class="math inline">\(\set{{\small\verb;low;}, {\small\verb;medium;}, {\small\verb;high;}}\)</span></li>
<li>weight fraction of <span class="math inline">\(\mathit{Si}\)</span>licon in the fragment (ordinal variate), with three possible values <span class="math inline">\(\set{{\small\verb;low;}, {\small\verb;medium;}, {\small\verb;high;}}\)</span></li>
<li><span class="math inline">\(\mathit{Type}\)</span> of glass fragment (nominal variate), with seven possible values <span class="math inline">\(\{{\small\verb;building_windows_float_processed;}\)</span>, <span class="math inline">\({\small\verb;building_windows_non_float_processed;}\)</span>, <span class="math inline">\({\small\verb;containers;}\)</span>, <span class="math inline">\({\small\verb;tableware;}\)</span>, <span class="math inline">\({\small\verb;headlamps;}\}\)</span></li>
</ul></li>
</ul>
<div id="tbl-glass-simple" class="sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-glass-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.1: Simplified glass-fragment population data
</figcaption>
<div aria-describedby="tbl-glass-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm small caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_non_float_processed;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_float_processed;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;containers;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_non_float_processed;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">9</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">10</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Let’s say we are interested only in units that have the <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> variate equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;tableware;}\)</span>.</span> Discarding all others we obtain a new, smaller population with four units:</p>
<div id="tbl-glass-tableware" class="sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-glass-tableware-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.2: Selection according to <span class="math inline">\(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}\)</span>
</figcaption>
<div aria-describedby="tbl-glass-tableware-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm small caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">9</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">10</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>were a bar <span style="display:inline-block;">“<span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\)</span>”</span> indicates the variate used for the selection.</p>
<p>As another example, we could be interested instead in those units that have <em>both</em> <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> <em>and</em> <span style="display:inline-block;"><span class="math inline">\(\mathit{Si}\)</span></span> variates equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;medium;}\)</span>.</span> We obtain a smaller population with five units:</p>
<div id="tbl-glass-ca-si-medium" class="sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-glass-ca-si-medium-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.3: Selection according to <span class="math inline">\(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;medium;}\)</span> and <span class="math inline">\(\mathit{Si}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;medium;}\)</span>
</figcaption>
<div aria-describedby="tbl-glass-ca-si-medium-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm small caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">3</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">4</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_float_processed;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">6</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;containers;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">9</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">10</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Populations formed in this way are called <span class="blue"><strong>subpopulations</strong></span> of the original one. They are statistical populations in their own right. The notion of “subpopulation” is a relative notion. Any population can often be considered as a subpopulation of some larger population having additional variates.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>From the population of <a href="#tbl-glass-simple" class="quarto-xref">table&nbsp;&nbsp;<span>22.1</span></a>:
<ul>
<li>Construct the <em>marginal</em> population with variate <span class="math inline">\(\mathit{Ca}\)</span></li>
<li>Report the frequency distribution for the marginal population above (remember that <span class="math inline">\(\mathit{Ca}\)</span> has <em>three</em> possible values)</li>
<li>Construct the subpopulation with variate <span class="math inline">\(\mathit{Si}\)</span> equal to <span class="math inline">\({\small\verb;high;}\)</span></li>
<li>Construct the subpopulation with variate <span class="math inline">\(\mathit{Type}\)</span> equal to <span class="math inline">\({\small\verb;headlamps;}\)</span> and the variate <span class="math inline">\(\mathit{Si}\)</span> equal to <span class="math inline">\({\small\verb;medium;}\)</span></li>
</ul></li>
</ul>
<p><em>Check your understanding of the reasoning behind the notions of marginal population and subpopulation with this exercise:</em></p>
<ul>
<li>From the population of <a href="#tbl-glass-simple" class="quarto-xref">table&nbsp;&nbsp;<span>22.1</span></a>, construct the subpopulation with variate <span class="math inline">\(\mathit{Type}\)</span> equal to <em>either</em> <span class="math inline">\({\small\verb;headlamps;}\)</span> <em>or</em> <span class="math inline">\({\small\verb;tableware;}\)</span>.</li>
</ul>
</div>
</div>
</section>
<section id="sec-conditional-freqs" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="sec-conditional-freqs"><span class="header-section-number">22.2</span> Conditional frequencies</h2>
<p>Given a statistical population with joint variates <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}X}, {\color[RGB]{238,102,119}Y}\)</span></span> (and possibly others), we define the <span class="blue"><strong>conditional frequency</strong></span> of the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}y}\)</span></span> of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}Y}\)</span>,</span> given or “conditional on” the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}x}\)</span></span> of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}X}\)</span>,</span> as the frequency of the value <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}y}\)</span></span> in the subpopulation selected by <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x}\)</span>.</span> This frequency is usually written</p>
<p><span class="math display">\[
f({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x})
\]</span></p>
<p>where <span style="display:inline-block;"><span class="math inline">\(f\)</span></span> is the symbol for the joint frequency of the population.</p>
<p>Consider for instance the glass-fragment population of <a href="#tbl-glass-simple" class="quarto-xref">table&nbsp;&nbsp;<span>22.1</span></a>. The conditional frequency of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}}\)</span></span> given <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}}\)</span></span> is the (marginal) frequency of <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}\)</span></span> in the subpopulation of <a href="#tbl-glass-tableware" class="quarto-xref">table&nbsp;&nbsp;<span>22.2</span></a>, from which we find</p>
<p><span class="math display">\[
f({\color[RGB]{238,102,119}\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}}) = \frac{1}{4}
\]</span></p>
<p>The collection of these conditional frequencies for all values of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}Y}\)</span></span> constitutes the <span class="blue">conditional frequency distribution</span> of <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{238,102,119}Y}\)</span></span> conditional on <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x}\)</span>.</span> In our example this distribution has three conditional frequencies:</p>
<p><span class="math display">\[\begin{aligned}
&amp;f({\color[RGB]{238,102,119}\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}}) = \frac{1}{4}
\\
&amp;f({\color[RGB]{238,102,119}\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;medium;}} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}}) = \frac{3}{4}
\\
&amp;f({\color[RGB]{238,102,119}\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;high;}} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}}) = 0
\end{aligned}\]</span></p>
<p>which sum up to <span style="display:inline-block;"><span class="math inline">\(1\)</span></span> as they should.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-exclamation-triangle" aria-label="exclamation-triangle"></i> Conditional on a <em>value</em> of a variate
</div>
</div>
<div class="callout-body-container callout-body">
<p>It doesn’t make sense to speak of the conditional frequency distribution of <span style="display:inline-block;"><span class="math inline">\(Y\)</span></span> “conditional <span class="yellow">on <span class="math inline">\(X\)</span>”</span>. Conditional frequencies and frequency distributions are always conditional on some value of a variate. If we consider all possible values of <span style="display:inline-block;"><span class="math inline">\(Y\)</span></span> <em>and</em> of <span style="display:inline-block;"><span class="math inline">\(X\)</span></span> we obtain a collection of frequencies that is <em>not</em> a distribution.</p>
</div>
</div>
<p>A conditional frequency can be calculated as the ratio of a joint and a marginal frequencies, in a way analogous to conditional probabilities (<a href="conditional_probability.html#sec-conditional-probs" class="quarto-xref">§&nbsp;<span>17.1</span></a>):</p>
<p><span class="math display">\[
f({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \nonscript\:\vert\nonscript\:\mathopen{} {\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x}) =
\frac{f({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x})}{f({\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x})} =
\frac{f({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x})}{
\sum_{\color[RGB]{238,102,119}y} f({\color[RGB]{238,102,119}Y\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}y} \mathbin{\mkern-0.5mu,\mkern-0.5mu}{\color[RGB]{34,136,51}X\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}x})}
\]</span></p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercises
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the conditional frequency distributions corresponding to the subpopulations of tables <a href="#tbl-glass-tableware" class="quarto-xref"><span>22.2</span></a> and <a href="#tbl-glass-ca-si-medium" class="quarto-xref"><span>22.3</span></a>. For example, for <a href="#tbl-glass-tableware" class="quarto-xref">table&nbsp;&nbsp;<span>22.2</span></a> this means calculating</p>
<p><span class="math display">\[\begin{aligned}
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathit{Si}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;})\ ,
\\
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathit{Si}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;medium;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;})\ ,
\\
&amp;\dotsc\ ,
\\
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;high;} \mathbin{\mkern-0.5mu,\mkern-0.5mu}\mathit{Si}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;high;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;})
\end{aligned}\]</span></p>
</div>
</div>
</section>
<section id="sec-association" class="level2 page-columns page-full" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="sec-association"><span class="header-section-number">22.3</span> Associations</h2>
<p>The analysis of subpopulations and conditional frequencies is important because it often reveals peculiar <span class="blue"><em>associations</em></span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> among different variates and groups of variates. Let’s illustrate what we mean by “association” with an example.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;In everyday language this is the same as “correlation”. The term “association” is used in statistics to avoid confusion with the Pearson correlation coefficient (see <a href="information.html#sec-entropy-mutualinfo" class="quarto-xref">§&nbsp;<span>18.5</span></a>)</p></div></div><p>Extract the subpopulation having variate <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;headlamps;}\)</span></span> from the population of <a href="#tbl-glass-simple" class="quarto-xref">table&nbsp;&nbsp;<span>22.1</span></a>:</p>
<div id="tbl-glass-headlamps" class="sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-glass-headlamps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.4: Selection according to <span class="math inline">\(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}\)</span>
</figcaption>
<div aria-describedby="tbl-glass-headlamps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm small caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>we notice that all units have variate <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span>.</span> In terms of conditional frequencies, this means</p>
<p><span class="math display">\[
\begin{aligned}
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}) = 1
\\
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;medium;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}) = 0
\\
&amp;f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;high;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}) = 0
\end{aligned}
\]</span></p>
<p>It is therefore impossible to observe other values of <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> in this new population.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;We are not claiming that this fact will be true if new units are considered; this important question will be discussed later.</p></div></div><p>On the other hand, if we extract the subpopulation having variate <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span></span> we obtain</p>
<div id="tbl-glass-ca-low" class="sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-glass-ca-low-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.5: Selection according to <span class="math inline">\(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}\)</span>
</figcaption>
<div aria-describedby="tbl-glass-ca-low-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm small caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="yellow">unit</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\nonscript\:\vert\nonscript\:\mathopen{}}\mathit{Ca}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Si}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{Type}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">1</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">2</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_non_float_processed;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">5</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;headlamps;}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="yellow">7</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;medium;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;building_windows_non_float_processed;}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="yellow">8</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;low;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;high;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\small\verb;tableware;}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>with conditional frequencies such as</p>
<p><span class="math display">\[
\begin{aligned}
&amp;f(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}) = \frac{2}{5}
\\[1ex]
&amp;f(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}) = \frac{1}{5}
\end{aligned}
\]</span></p>
<p>and so on. The reverse is therefore <em>not</em> true: if <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> is equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span>,</span> that does <em>not</em> mean that it’s impossible to observe other <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> values besides <span style="display:inline-block;"><span class="math inline">\({\small\verb;headlamps;}\)</span>.</span> Note especially how these frequencies differ:</p>
<p><span class="math display">\[
\begin{gathered}
f(\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}) = 1
\\[1ex]
f(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;} \nonscript\:\vert\nonscript\:\mathopen{} \mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}) = \frac{2}{5}
\end{gathered}
\]</span></p>
<p>In the original population we have, figuratively speaking, the following interesting association:</p>
<p><span class="math display">\[
\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}\ \mathrel{\color[RGB]{34,136,51}\Rightarrow}\
\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}
\qquad\text{\small but}\qquad
\mathit{Ca}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;low;}\  \mathrel{\color[RGB]{238,102,119}\nRightarrow}\
\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;headlamps;}
\]</span></p>
<p>This kind of associations is often useful. Suppose for instance that you are asked to pick a unit with <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span></span> in the original population; but it’s difficult to measure a unit’s <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> value, while it’s easy to measure its <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> value. Then you could instead search for a unit having <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;headlamps;}\)</span></span> (easier search), and you would be sure that the unit you found also has <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> equal to <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span>.</span></p>
<p><br>
</p>
<p>The example above, where some values of a variate completely exclude some values of another, is a special one. More often we find that there are small or large changes in the frequency distribution of some variate, depending on the subpopulation considered.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Calculate the (marginal) frequency distribution for the <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span></span> variate for the glass-fragment population of <a href="#tbl-glass-simple" class="quarto-xref">table&nbsp;&nbsp;<span>22.1</span></a>. Is the value <span style="display:inline-block;"><span class="math inline">\({\small\verb;low;}\)</span></span> more frequent than <span style="display:inline-block;"><span class="math inline">\({\small\verb;medium;}\)</span>?</span> or vice versa?</p></li>
<li><p>Calculate the frequency distribution for <span style="display:inline-block;"><span class="math inline">\(\mathit{Ca}\)</span>,</span> conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{Type}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\small\verb;tableware;}\)</span></span> (see <a href="#tbl-glass-tableware" class="quarto-xref">table&nbsp;&nbsp;<span>22.2</span></a>). How does this frequency distribution differ from the one you calculated above? Come up with possible ways to exploit this difference in concrete applications.</p></li>
</ul>
</div>
</div>
<section id="associations-can-be-very-counter-intuitive" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="associations-can-be-very-counter-intuitive">Associations can be very counter-intuitive</h3>
<p>It is usually best to assess associations by explicitly calculating all relevant conditional frequencies, rather than jumping to intuitive conclusions after having examined just a few. Here’s an example.</p>
<p><br>
</p>
<p>Consider the statistical population defined as follows:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="component_repair.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><ul>
<li><p><em>units:</em> all reparations done by a repair company on a particular kind of electronic components, which is extremely delicate and usually very difficult to repair. The population has 26 units (every unit actually represents a batch 100 reparations, so the population really refers to 2600 reparations).</p></li>
<li><p>a joint <em>variate</em>, consisting in three binary ones:</p>
<ul>
<li><p><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\)</span> of the repair procedure, with values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span>;</span></p></li>
<li><p>repair <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\)</span>,</span> with values <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span>,</span> representing a traditional reparation method and one introduced more recently;</p></li>
<li><p><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span> of the repair procedure, with values <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span>.</span></p></li>
</ul></li>
</ul>
<div id="tbl-reparations" class="sm striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reparations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.6: Reparations (each row is one unit, representing 100 reparations).<br>
file <a href="datasets/repair_data.csv"><code>repair_data.csv</code></a>
</figcaption>
<div aria-describedby="tbl-reparations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-sm table-striped small caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;success;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color[RGB]{238,102,119}{\small\verb;fail;}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>The repair company claims that, in this population, the <span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span> repair method is more effective than the <span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span>.</strong> Can you back up their claims?:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-user-edit" aria-label="user-edit"></i> Exercise (one of the most fun of the course!)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the population data above. The calculations can be done with any tools you like.</p>
<ul>
<li><p>Examine the whole population first:</p>
<ol type="1">
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> (note that we are disregarding the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\)</span>).</span></p></li>
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;old;}}\)</span>.</span></p></li>
<li><p>Compare the two conditional frequency distributions above. Which of the two repair methods seems more effective?<br>
Are the claims of the repair company justified?</p></li>
</ol></li>
<li><p>Now examine the reparations that have been done <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span>:</span></p>
<ol start="4" type="1">
<li><p>Before doing any calculations, what do you expect to find? should the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> repair method be more effective than the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></span> one, for onsite reparations?</p></li>
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span>.</span></p></li>
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span>.</span></p></li>
<li><p>Compare the two conditional frequency distributions for this <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;onsite;}}\)</span></span> case. Which of the two repair methods seems more effective?<br>
How do you explain this result in the light of what you found in step 3.?</p></li>
</ol></li>
<li><p>Now examine the reparations that have been done <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span>ly:</span></p>
<ol start="8" type="1">
<li><p>Before doing any calculations, what do you expect to find? should the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> repair method be more effective than the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></span> one, for reparations done remotely?</p></li>
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span>.</span></p></li>
<li><p>Calculate the frequency distribution of the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{238,102,119}Outcome}\)</span></span> variate, conditional on <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{34,136,51}{\small\verb;old;}}\)</span></span> and <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\mathclose{}\mathord{\nonscript\mkern 0mu\textrm{\small=}\nonscript\mkern 0mu}\mathopen{}{\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span>.</span></p></li>
<li><p>Compare the two conditional frequency distributions for this <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{102,204,238}{\small\verb;remote;}}\)</span></span> case. Which of the two repair methods seems more effective?<br>
How do you explain this result in the light of what you found in steps 3. and 7.?</p></li>
</ol></li>
<li><p>Summarize and explain all your findings.<br>
Can the repair company claim that the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;new;}}\)</span></span> repair method is better than the <span style="display:inline-block;"><span class="math inline">\({\color[RGB]{34,136,51}{\small\verb;old;}}\)</span>?</span><br>
</p></li>
<li><p>Suppose you need to send an electronic component for repair to this company.</p>
<ol type="a">
<li><p>If you could choose both the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\)</span></span> and the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\)</span></span> of the repair, which would you choose? why?</p></li>
<li><p>If you could only choose the repair <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{34,136,51}Method}\)</span>,</span> but have no control over the <span style="display:inline-block;"><span class="math inline">\(\mathit{\color[RGB]{102,204,238}Location}\)</span>,</span> which method would you choose? why?</p></li>
</ol>
<p>Is there other information, missing from the description of the population, that should be known before answering the questions above?</p></li>
</ul>

</div>
</div>
<div class="no-row-height column-margin column-container"><div class="callout-margin-content">
<p><img src="lego_paradox.jpg" class="img-fluid" style="width:100.0%"></p>
</div></div><div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-book" aria-label="book"></i> Study reading
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>§§2.2–2.4 and 2.7–2.10 of Fenton &amp; Neil: <a href="references.html"><em>Risk Assessment and Decision Analysis with Bayesian Networks</em></a></p></li>
<li><p>Lindley &amp; Novick 1981: <a href="references.html"><em>The role of exchangeability in inference</em></a> This can be a difficult reading. Try to get the main message.</p></li>
<li><p>Malinas &amp; Bigelow 2004/2016: <a href="https://plato.stanford.edu/archives/fall2016/entries/paradox-simpson/"><em>Simpson’s paradox</em></a></p></li>
</ul>
</div>
</div>


</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./statistics.html" class="pagination-link" aria-label="[Statistics]{.yellow}">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title"><span class="yellow">Statistics</span></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./samples.html" class="pagination-link" aria-label="[Infinite populations and samples]{.yellow}">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title"><span class="yellow">Infinite populations and samples</span></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>